- cmd/server.go
- cmd/snapshot.go
- cmd/types.go
- pkg/initializer/initializer.go
- pkg/server/httpAPI.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/snapshot.go
- pkg/snapstore/snapshot_test.go
- pkg/snapstore/snapstore_test.go
Fixes https://github.com/gardener/etcd-backup-restore/issues/3.
Added exponential garbage collection policy
- Keep only the last 24 hourly backups and of all other backups only the last backup in a day
-  Keep only the last 7 daily backups and of all other backups only the last backup in a week
-  Keep only the last 4 weekly backups
Unit tests are added for same
> Add exponential garbage collection policy 

- README.md
Update clone address with https url.  
Clone action will fail with `permission denied` error using original url(`git@github.com:gardener/etcd-backup-restore.git`).
It is ok to use https url to clone this project, so it would be better to use https one in my opinion.
NONE
```improvement operator
```
> update clone address with https url

- cmd/server.go
- cmd/types.go
- pkg/server/httpAPI.go
This PR add the exposes the `debug/pprof/*` endpoint to dynamically profile cpu, heap consumption. To enable profiling one has to explicitly set `enable-profiling`  on `server` subcommand.
Fixes #
```noteworthy operator
Dynamic profiling support is added. Now we expose the `debug/pprof/*` endpoint to dynamically profile cpu, heap consumption. To enable profiling one has to explicitly set `enable-profiling`  on `server` sub-command.
```
> Add dynamic profiling support

- cmd/restore.go
- cmd/server.go
- cmd/snapshot.go
- cmd/types.go
- pkg/initializer/initializer.go
- pkg/server/httpAPI.go
- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/snapshot.go
- pkg/snapstore/types.go
This PR fixes race-conditions that arise when etcd backup-restore occurs.
Fixes #
This PR fixes race-conditions that arise when etcd backup-restore occurs.
- The http handler in the backup-restore should wait till snapshotter has stopped before starting data directory initialization.
```improvement operator
```
> Race condition fix.

- cmd/server.go
- cmd/snapshot.go
- cmd/types.go
- pkg/etcdutil/defrag.go
- pkg/etcdutil/defrag_test.go
- pkg/etcdutil/etcdutil.go
- pkg/etcdutil/etcdutil_suite_test.go
- pkg/etcdutil/types.go
- pkg/snapshot/restorer/restorer_suite_test.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/gcs_snapstore.go
Fixes #
```improvement operator
Etcd-backup-restore utility when started in server mode will start defragmenting etcd member data directory periodically, so that db size will be under control. You can set defragmentation period in number of hours by setting `defragmentation-period-in-hours` flag on `etcdbrctl server` command.
```
> Add periodical defragmentation support for ETCD

- pkg/initializer/initializer.go
- pkg/snapshot/restorer/restorer.go
This PR is a hotfix that fixes the bug where etcd can start with partially applied snapshot. If the incremental snapshot is partially applied due to failure in between, the etcd data is consistent though not up-to-date. This PR fixes this issue.
Fixes #
```improvement operator
At the time of restoration, the etcd data directory will be restored to temporary directory with suffix `.part` i.e.`<path-to-etcd-data-dir>.part`. On successful restoration we will replace actual etcd data directory with this. This brings standard and more cleaner approach to restoration. 
```
> Remove the data directory in case of a failed restore.

- cmd/initializer.go
- cmd/miscellaneous.go
- cmd/restore.go
- cmd/server.go
- cmd/snapshot.go
- cmd/types.go
- pkg/etcdutil/defrag.go
- pkg/etcdutil/defrag_test.go
- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/local_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/s3_snapstore_test.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/types.go
- pkg/snapstore/utils.go
- test/e2e/integration/cloud_backup_test.go
Earlier we used to spawn go routine for all chunks simultaneously which was causing network traffic. This PR refactor the multi-part/chunk upload code. Now, we can configure the number of parallel chunk upload upper limit.
Fixes #
Please test both snapshot and server sub-command against all cloud providers.
```noteworthy user
Now, snapshot upload happens in chunk. One can configure the number of parallel chunk uploads by setting command line argument `max-parallel-chunk-uploads`. Default is set to 5.
```
> Refactor chunk upload and make the parallel uploads configurable

- chart/Chart.yaml
- chart/templates/etcd-bootstrap-configmap.yaml
- chart/templates/etcd-client-service.yaml
- chart/templates/etcd-statefulset.yaml
- chart/values.yaml
**What this PR does / why we need it**: 
The only helm chart available for etcd-backup-restore was in gardener, this one adds a helm chart to the upstream.
Fixes #
* I copied the chart from gardener repo as is and only updated the dummy image names to the ones in use in gardener
* I didn't do any further modification on purpose since gardener seems to be main user better to keep this in sync as much as possible. This one is open to discussions.
Historical discussion in the slack channel can be found in: https://kubernetes.slack.com/archives/CB57N0BFG/p1539340130000100
```improvement operator
There is now a helm chart to deploy etcd-backup-restore.
```
> Add helm chart

- pkg/snapshot/snapshotter/snapshotter.go
Currently we blindly update take new full snapshot, even if last full snapshot was taken on same etcd revision. This PR skips duplicate full snapshot in case there is no update on etcd since last full snapshot. 
Fixes #
```improvement user
NONE
```
> Avoid duplicate full snapshot 

- cmd/snapshot.go
- pkg/initializer/validator/datavalidator.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
Added the option to disable delta snapshots, by setting the `--delta-snapshot-period-seconds` flag to any value lesser than 1.
Fixes #94 
```improvement operator
Added the option to disable delta snapshots, by setting the 'delta-snapshot-period-seconds' flag to any value lesser than 1.
```
> Allow disabling delta snapshots

- .ci/pipeline_definitions
> We have just released Go 1.11.5 and Go 1.10.8 to address a recently reported security issue. We recommend that all users update to one of these releases (if you’re not sure which, choose Go 1.11.5).
>
> This DoS vulnerability in the crypto/elliptic implementations of the P-521 and P-384 elliptic curves may let an attacker craft inputs that consume excessive amounts of CPU.
>
> These inputs might be delivered via TLS handshakes, X.509 certificates, JWT tokens, ECDH shares or ECDSA signatures. In some cases, if an ECDH private key is reused more than once, the attack can also lead to key recovery.
>
> The issue is CVE-2019-6486.
n/a
```improvement operator
NONE …
```
> Upgrade golang version to 1.11.5

- .ci/build
- cmd/miscellaneous.go
- cmd/root.go
- cmd/server.go
- cmd/snapshot.go
- cmd/types.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/local_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/types.go
- pkg/version/version.go
Currently we don't close old client at the time full snapshot. Also, for delta snapshot `json.Marshal` doesn't help in streaming the marshalled data. This modifies the logic there. This PR also, adds the version flag to get binary version info, like from which git commit it was built.
Fixes partially #95 
Please verify it thoroughly. Make use of etcd benchmark tool and monitor the performance.
```improvement operator
NONE
```
> Stop etcd watch client when not in use and streamline the Json encoding for delta snapshot

- pkg/snapstore/s3_snapstore_test.go
This PR fixes a data race condition in the S3 mock client used for the unit tests for the snapstore package.
```improvement operator
NONE
```
> Fix S3 mock client race condition

- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
Currently, for case like etcd-events where we don't configure storage provider to disable backups, the backup dependent sanity checks fails with panic. This PR fixes the issue.
Fixes #
```improvement operator
In case of storage provider is not configured, i.e. backup disabled, we skip the backup dependent sanity checks.
```
> Skip snap store specific sanity check when not configured

- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
This PR is cherry-pick of #122 
Fixes #
```noteworthy user
In case of storage provider is not configured, i.e. backup disabled, we skip the backup dependent sanity checks.
```
> [hotfix] Skip snap store specific sanity check when not configured

- pkg/snapstore/s3_snapstore_test.go
Fix multipart upload functionality for S3 mock client for snapstore unit tests, so that the check for the ordering of the upload parts by `PartNumber` will now work.
```improvement operator
NONE
```
> Fix upload functionality in S3 mock client for unit tests

- pkg/snapstore/snapshot.go
- pkg/snapstore/snapshot_test.go
This PR allows for correct sorting of snapstore in cases where snapshots have same `CreatedOn` timestamp.
```improvement operator
NONE
```
> Fix snapstore sorting for snapshots with same timestamp

- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/types.go
This PR optimises delta snapshots further by avoiding json marshalling multiple times, resulting in memory spike. 
Fixes #102 
Please cross check the delta snapshot json rendering and restoration.
Here are the graphs I observed:
WIth this PR:
With old master:
Observations:
* Full snapshot spikes are common in both. independent of db size. Second graph the full snapshot time syncs with first 2 benchmarks , so you might miss-out but 3rd  full snapshot spike is clear.
* Memory consumed is reduced significantly.
* delta-snapshot-memory limit is 10 mb 
```improvement operator
NONE
```
> Optimise delta snapshot to use one time json marshalling

- .ci/pipeline_definitions
https://golang.org/doc/go1.12
Fixes #
```improvement operator
The golang version has been upgraded to `v1.12.0`.
```
> Update golang to 1.12.0

- chart/templates/etcd-statefulset.yaml
- chart/values.yaml
- cmd/initializer.go
- cmd/restore.go
- cmd/server.go
- cmd/types.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/restorer/types.go
This PR fixes the bug where large size etcd data (greater than 2GB) could not be restored due to the backend quota size not being configured on the embedded etcd instance that is started on the backup sidecar to apply delta snapshots during restoration.
Fixes #133 
```noteworthy user
Added the `embedded-etcd-quota-bytes` flag to allow configuring the backend quota size of the embedded etcd instance used during restoration of data.
```
> Pass db quota size config to embedded etcd used by restorer

- chart/templates/etcd-statefulset.yaml
- chart/values.yaml
- cmd/initializer.go
- cmd/restore.go
- cmd/server.go
- cmd/types.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/restorer/types.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/s3_snapstore_test.go
- pkg/snapstore/snapshot.go
- pkg/snapstore/snapshot_test.go
This PR simply cherry-picks the recent fixes from master.
Fixes #
As usual like pre-release step, please create a shoot using gardener. And check if etcd-events and etcd-main are working fine there.
```noteworthy user
Added the `embedded-etcd-quota-bytes` flag to allow configuring the backend quota size of the embedded etcd instance used during restoration of data.
```
> Cherry pick fixes from master

- chart/templates/etcd-bootstrap-configmap.yaml
- chart/templates/etcd-statefulset.yaml
- chart/values.yaml
This PR fixes the typo for `embedded-etcd-quota-bytes` in the helm chart.
Fixes #
```improvement operator
NONE
```
> Fix embedded-etcd-quota-bytes flag on helm chart

- chart/templates/etcd-statefulset.yaml
- cmd/server.go
This PR optimizes readiness probe on etcd by marking the health endpoint as ready before taking the first full snapshot rather than after, as was being done previously. This reduces etcd downtime during cluster updates.
```improvement operator
Reduced etcd downtime by optimizing readiness probe.
```
> Optimize etcd readiness probe

- build/Dockerfile
- chart/templates/etcd-statefulset.yaml
- cmd/server.go
This is a cherry-pick of https://github.com/gardener/etcd-backup-restore/pull/146 and https://github.com/gardener/etcd-backup-restore/pull/151
Fixes #
```improvement operator
Reduced etcd downtime by optimizing readiness probe.
```
```improvement operator
Updated the base image of alpine in docker container to 3.9.3.
```
> Cherry pick etcd readiness probe optimization and alpine version update

- cmd/server.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/types.go
This PR defers the first full snapshot on etcd startup, by instead taking a delta snapshot initially and then taking a full snapshot. This helps speeding up setting the readiness probe of etcd to active. If no previous full snapshot exists in the backup or it has been more than 24 hours since the last full snapshot, a full snapshot will be taken on startup, followed by delta snapshots, as was the case earlier.
Fixes #150 
~Snapshotter `Run()` has been modified with new `delaySeconds` parameter to allow setting deferred snapshot timers~. Also, for the moment, I have hard-coded `24 hours` for checking if previous snapshot …
> Defer first full snapshot on etcd startup

- cmd/server.go
This PR fixes stop-channel signal handling while taking the first delta snapshot for the `server` subcommand.
Fixes #
```improvement operator
NONE
```
> Fix stop-signal handling during initial delta snapshot

- cmd/server.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapstore/snapshot.go
- pkg/snapstore/snapshot_test.go
This PR is a cherry pick of https://github.com/gardener/etcd-backup-restore/pull/160 and https://github.com/gardener/etcd-backup-restore/pull/161
Fixes #
```improvement user
Fixed the sorting of snapshots. 
```
> Cherry pick stop signal handling and snapshot sorting fixes

- pkg/snapstore/abs_snapstore.go
Fixes a seg fault in azure snapstore code where type assertion is handled incorrectly.
Fixes #
#163 
```improvement operator
```
> Fixed seg fault when type assertion fails for azure container properties fetch.

- cmd/server.go
This PR fixes the error handling while taking initial delta snapshot. Currently, if the initial delta snapshot fails, we retry the etcd probe and try taking the initial delta snapshot again, repeatedly until it succeeds. In the case where backup sidecar had already taken some snapshots and then stopped for some time while etcd is still running and is also compacted in that interval, when sidecar starts again, there's a chance the watch for initial delta snapshot will fail because the latest revision from the snapstore is not available anymore on etcd (as it was compacted). This throws backup sidecar into an infinite failure loop.
This PR fixes this behavior by taking a full snapshot on an …
> Fix error handling for initial delta snapshot

- chart/etcd-backup-restore/templates/backup-client-service.yaml
- chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
- chart/etcd-backup-restore/templates/etcd-client-service.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/templates/etcd-tls-secret.yaml
- chart/etcd-backup-restore/values.yaml
This PR fixes the liveness probe command in the helm chart, which previously used to pass an illegal `--config-file` flag to the `etcdctl` command.
The PR also brings all port numbers in the helm chart into the `values.yaml` file.
Fixes #
```improvement operator
Fixed liveness probe command in helm chart.
```
> Fix liveness probe command in helm chart

- cmd/server.go
- pkg/etcdutil/defrag.go
- pkg/etcdutil/defrag_test.go
- pkg/server/httpAPI.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR adds functionality to trigger on-demand full snapshots via the HTTP endpoint `/snapshot/full`.
This PR also fixes a few unhandled scenarios for the case when snapstore provider is not configured, such as etcd readiness probe handling and defragmentation. It also refactors the server command to make it more modular.
Fixes #113 
Also refactored the `TriggerFullSnapshot` and `DefragDataPeriodically` methods, as well as the order of object creation in `NewServerCommand` in order to pass the `Snapshotter` to the `HTTPHandler`.
Will add unit tests shortly.
```noteworthy user
Added functionality to trigger on-demand full snapshots via the HTTP endpoint …
```
> Expose triggering on-demand full snapshot via HTTP endpoint

- chart/etcd-backup-restore/values.yaml
In order to better utilize the Seed nodes, the pods of the Shoot control plane should only request the resources they really need.
Based on the evaluation of the VPA recommendations for all Shoots on our Canary and Live landscape over a few weeks, the new value reflects the maximum recommendation for the ETCD backup-restore container.
This maximum value also ensures that the ETCD pods aren't evicted from a node at normal scenarios because of exhausted node resources.
Fixes #
```NONE```
> Adapt pod requests based on VPA recommendations

- pkg/metrics/metrics.go
- pkg/metrics/metrics_suite_test.go
- pkg/metrics/metrics_test.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR initializes all Prometheus metrics to their respective zero-values before exposing them.
Fixes #167 
```improvement operator
NONE
```
> Initialize Prometheus metrics before exposing

- cmd/server.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_suite_test.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapstore/utils.go
This PR fixes snapshotter behavior for the case when starting snapshotter with `startWithFullSnapshot` set to false.
Fixes #
```improvement operator
NONE
```
> Fix snapshotter behavior when starting it without full snapshot

- chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
- chart/etcd-backup-restore/values.yaml
- cmd/initializer.go
- cmd/server.go
- cmd/types.go
- pkg/initializer/initializer.go
- pkg/initializer/types.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/datavalidator_test.go
- pkg/initializer/validator/types.go
- pkg/server/httpAPI.go
- test/e2e/integration/cloud_backup_test.go
Main motivation behind this is to help external entity configure revision in case of bucket change or object store prefix change.
Fixes #
```improvement operator
Added new flag `experimental-fail-below-revision` flag for initializer and `/initialization/start` http call
```
> Add experimental fail below revision flag

- pkg/snapshot/snapshotter/snapshotter.go
Currently, in case etcd restarts and there are some events collected by backup restore sidecar in memory, on receiving stop signal via initialisation request due restart of etcd, the next delta snapshot taken post initialization  will store duplicate entries in last delta snapshot. Which might lead to corrupt last delta snapshot. This PR fixed the issue by removing those duplicate events in memory.
Fixes #
```improvement operator
[Fix] Cleanup in-memory events before stopping snapshotter.
```
> Cleanup in-memory events before stopping snapshotter

- pkg/snapshot/snapshotter/snapshotter.go
Currently, in case etcd restarts and there are some events collected by backup restore sidecar in memory, on receiving stop signal via initialisation request due restart of etcd, the next delta snapshot taken post initialization will store duplicate entries in last delta snapshot. Which might lead to corrupt last delta snapshot. This PR fixed the issue by removing those duplicate events in memory.
Fixes #
This PR is cherry-pick of https://github.com/gardener/etcd-backup-restore/pull/190
```improvement operator
[Fix] Cleanup in-memory events before stopping snapshotter.
```
> [hotfix] Cleanup in-memory events before stopping snapshotter

- README.md
- cmd/server.go
- doc/usage/metrics.md
- pkg/metrics/metrics.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR exposes new metric `etcdbr_snapshot_required` that exposes a Gauge metric to indicate whether a snapshot is required to be taken, based on whether a new etcd revision is observed.
Fixes #
Also contains minor linting corrections.
```improvement developer
Expose new metric `etcdbr_snapshot_required`.
```
> Expose etcdbr_snapshot_required metric

- .ci/unit_test
- pkg/miscellaneous/miscellaneous.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_suite_test.go
- pkg/snapshot/restorer/restorer_test.go
Added more negative tests for restore of snapshots. 
Following test been added - 
1. Restore with embedded etcd quota not set 
2. Restore with invalid cluster URL
3. Restore with invalid restore directory
4. Restore with snapdir and snapname set to ""
5. Restore with invalid snapdir and snapname
6. Restore with no delta snapshots
7. Restore with corrupted snapstore
8. Restore with etcd client is unavailable
9. Restore with etcd data dir not cleaned up before restore
10. Restore with snapshotter running in parallel
Fixes partially #73 #104 
Enhanced the populate script to capture delete of keys.
Some refactoring is done to segregate the tests into 2 categories - 
1. Running …
> Added negative tests for restore of snapshots

- README.md
- doc/development/new_cp_support.md
- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/datavalidator_test.go
- pkg/initializer/validator/types.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapstore/failed_snapstore.go
- pkg/snapstore/types.go
- pkg/snapstore/utils.go
- Because of incorrect error handling at revision consistency check, the etcd-backup-restore used to fail the validation and trigger restore for valid data directory. This was noticed when network was down at validation time but available at restore time. This PR fixes the issue.
- Additionally uses etcd API for etcd snap directory validation. We don't have to maintain code here anymore.
- Improves the test coverage for validator package.
Fixes #
```improvement user
Fix the error handling in revision consistency check leading to restoration on valid etcd data directory.
```
> Fix the revision consitency check error handling

- .ci/unit_test
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- Makefile
- pkg/server/httpAPI.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- test/utils/utils.go
Fixes #114
```improvement user
Expose http API to trigger out-of-schedule delta snapshot.
```
> [Feature] Expose api to trigger out-of-schedule delta snapshot

- pkg/snapshot/snapshotter/snapshotter.go
This PR fixes an issue where `etcdbr_snapshot_required` metric was not getting reset to 0 for cases where full snapshot was skipped due to no events collected. 
Fixes #
Saw this issue with a cluster that was woken up from hibernation and had no etcd events since previous hibernation, so both initial delta snapshot as well as subsequent full snapshot were skipped, but `etcdbr_snapshot_required` for full snapshot was still 1, due to which a false alert for `KubeEtcdFullBackupFailed` was fired.
```improvement operator
NONE
```
> Fix etcdbr_snapshot_required metric when skipping full snapshot

- README.md
- chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/templates/etcd-tls-secret.yaml
- chart/etcd-backup-restore/templates/etcdbr-ca-secret.yaml
- chart/etcd-backup-restore/templates/etcdbr-tls-secret.yaml
- chart/etcd-backup-restore/values.yaml
- cmd/server.go
- cmd/types.go
- doc/usage/generating_ssl_certificates.md
- pkg/server/httpAPI.go
This PR introduces TLS support for the etcd-backup-restore server. TLS can be enabled via the new `--enable-tls` flag, which also requires the TLS cert and key files in PEM format to be passed via `--server-tls-cert` and `--server-tls-key` flags. This PR also introduces security headers `HTTP-Strict-Transport-Security` and `Content-Security-Policy` for the HTTP responses when TLS is enabled.
Fixes #189 #187 
Renamed `tls` to `etcdTls` in helm values file, to differentiate between etcd tls config and etcdbr server tls config. Bootstrap script updated to use apk's wget instead of busybox wget in the case where …
> Add TLS support for backup-restore server

- .ci/integration_test
This PR fixes recent apt issue for installing pip tool during integration test setup.
Fixes #
```improvement developer
Fix integration test setup script.
```
> Fix integration test setup script

- pkg/defragmentor/defrag.go
- pkg/defragmentor/defrag_test.go
- pkg/server/backuprestoreserver.go
- pkg/server/httpAPI.go
- pkg/server/types.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/types.go
This PR enhances HTTP API to return snapshot metadata when triggering out-of-schedule full and delta snapshots. It also adds a new API at `/snapshot/latest` to fetch details of latest full and delta snapshots. The metadata is written in http response body in JSON format.
Fixes #213 
```noteworthy user
HTTP API for triggering out-of-schedule full and delta snapshots now returns snapshot metadata in response body in JSON format. 
```
```improvement user
Added new HTTP API for fetching details of latest full and delta snapshots, in JSON format. 
```
> Return metadata for latest and triggered snapshots

- doc/usage/metrics.md
- pkg/metrics/metrics.go
- pkg/miscellaneous/miscellaneous.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR adds two new metrics `etcdbr_snapstore_latest_deltas_total` and `etcdbr_snapstore_latest_deltas_revisions_total`, which provide information about the delta snapshots since the latest full snapshot in the snapstore (object store bucket). We assume that etcd-backup-restore process is the only handler of snapshots in the respective snapstore bucket, in order to maintain integrity of these metrics.
Fixes #
```improvement user
Add metrics `etcdbr_snapstore_latest_deltas_total` and `etcdbr_snapstore_latest_deltas_revisions_total` to provide information about the delta snapshots since the latest full …
```
> Add snapstore bucket-related metrics

- chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
- doc/usage/getting_started.md
- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
last full snapshot is within 24hr
Fixes https://github.com/gardener/etcd-backup-restore/issues/221
```improvement operator
Skip the first full snapshot on start,  if initial delta snapshot is taken and last full snapshot is recent enough than 24hr.
```
> Skip the full snapshot if initial delta snapshot is taken and

- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR fixes a bug with metrics initialization that surfaced due to recent change in initial snapshot logic, due to which false alerts were being raised.
Fixes #
```improvement operator
Fix snapshot metric initialization.
```
> Fix snapshot metrics initialization

- .ci/integration_test
- .test-defs/IntegrationTest.yaml
- go.sum
This PR adds support for running integration tests on [TestMachinery](https://github.com/gardener/test-infra) framework. The tests can be triggered from the TM Concourse dashboard, so that integration tests are run on a shoot cluster spawned by TestMachinery.
Fixes #107 
```improvement developer
Add TestMachinery integration.
```
> Integrate with Test Machinery

- .gitignore
- chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- doc/usage/getting_started.md
- pkg/snapstore/ecs_s3_snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/types.go
- pkg/snapstore/utils.go
Signed-off-by: lcavajani <lcavajani@suse.com>
This PRs adds `Dell EMC ECS` Snapstore for `S3` protocol. 
It is fully compatible with AWS-SDK S3 so I have reused the existing S3 snapstore.
```noteworthy user
Add support for **Dell EMC ECS** object store with `S3` protocol
```
> add Dell EMC ECS S3 snapstore

- testmachinery/flavors/min-shoot-flavor.yaml
I saw a coreos Shoot being created from this test flavor.
Starting from September 22, 2020, coreos AMIs are no longer available - ref https://stable.release.core-os.net/index.html.
/kind cleanup
```improvement operator
NONE
```
> Switch test flavor from coreos to gardenlinux

- .gitignore
- pkg/snapstore/generic_s3_snapstore.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/types.go
- pkg/snapstore/utils.go
Adds support for OpenShift Container Storage (OCS) S3-compatible snapstore. Also refactors the existing ECS snapstore to avoid code duplication since the 2 snapstores are quite similar.
Fixes #
See also https://github.com/gardener/etcd-druid/pull/98.
```improvement operator
Added support for OpenShift Container Storage (OCS) S3 storage type.
```
> Add support for OCS S3 snapstore

- .ci/build
- .ci/integration_test
- .ci/unit_test
- pkg/initializer/initializer.go
- pkg/snapshot/restorer/types.go
- pkg/snapshot/restorer/types_test.go
- test/e2e/integration/cloud_backup_test.go
- test/e2e/integrationcluster/backup_test.go
Fixed the issue with consecutive restoration if backup-restore sidecar doesn't restart in between.
The copy of the `e.Config.RestoreOptions` was a [shallow copy](https://github.com/gardener/etcd-backup-restore/blob/d4db4661562d91584ddfb12274b8a10c244b6082/pkg/initializer/initializer.go#L121) which means that the following [_temporary_ change](https://github.com/gardener/etcd-backup-restore/blob/d4db4661562d91584ddfb12274b8a10c244b6082/pkg/initializer/initializer.go#L122) to the restoration directory is actually a change to the original configuration and a bit more permanent than intended. I.e. a subsequent restoration (without an intervening backup-restore process restart) will use the _temporary_ folder as the …
> Fixed the issue with consecutive restoration.

- .ci/check
Check script was showing error when the user was not root. This
commit fixes that. Also, the check script was not running on mac
due to readlink error. The error is fixed as well.
Check script was showing error when the user was not root. This
commit fixes that. Also, the check script was not running on mac
due to readlink error. The error is fixed as well.
Fixes #
```improvement operator
NONE
```
> Enabled check script to run on mac and for normal user.

- pkg/snapstore/oss_snapstore_test.go
- pkg/snapstore/s3_snapstore_test.go
- pkg/snapstore/swift_snapstore_test.go
An error is appearing printing this: conversion from int to string yields a
string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
This error is appearing while running unit tests with golang version
1.15 . This error is fixed in this PR.
Fixes #
```improvement operator
```
> Fixed an error in unit test cases that appears due to use of latest golang.

- pkg/server/backuprestoreserver.go
This PR fixes missing full snapshots on shoot unhibernation. Setting the previous full snapshot existence check to 23.5 hours provides a buffer of 30 minutes for the pod to become ready to take the first full snapshot everyday in the case where full snapshot schedule lies within the shoot's hibernation period.
Fixes #258 
```improvement operator
Fix missing alternate full snapshots for some unhibernating shoots.
```
> Fix missing alternate full snapshots

- .ci/integration_test
- .ci/performance_regression_test
- chart/etcd-backup-restore/values.yaml
This PR fixes failing TM tests due to etcd version mismatch.
Fixes #
```improvement operator
NONE
```
> Fix etcd image for tests

- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/datavalidator_test.go
- pkg/initializer/validator/types.go
- pkg/initializer/validator/validator_suite_test.go
- pkg/snapshot/restorer/restorer.go
WALs file can have data revisions which are ahead of data revisions present in DB file, if etcd terminates abnormally and fails to flush the changes from WALs to Bolt DB ,this lead to  unnecessary data restoration.
This PR eliminates this unnecessary data restoration. Starting the embedded etcd on data dir, ping the embedded etcd for 60s to get the latest revision from etcd, after that compare this latest revision and latest revision of back-up data.
Fixes #260 
```improvement operator
Validator now double checks latest revision by starting an embedded etcd if DB-based revision check fails. This can potentially avoid unnecessary data restoration when etcd …
```
> Double check latest revision by starting an embedded etcd if revision check based on data dir fails during data validation 

- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/validator_suite_test.go
- pkg/snapshot/restorer/init.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/restorer/types.go
Added CLI-flags (`max-call-send-message-size`, `max-request-bytes` and `max-txn-ops`) to enable restoration for delta snapshots with large amount of data (large number of events or events with large data).
Fixes #263 
```improvement operator
Added CLI-flags (`max-call-send-message-size`, `max-request-bytes` and `max-txn-ops`) to enable restoration for delta snapshots with large amount of data (large number of events or events with large data).
```
> Added CLI-flags to enable restoration for delta snapshots with large amount of data

- .ci/unit_test
Currently, tests  run for `cmd` and `pkg` . But there is no provision to run tests just on any package of etcd-backup-retstore. This PR adds the support. It makes easier for developer to write/modify packages and test on just that package iteratively.
> Added support for running tests suites from user specified packages.

- cmd/options.go
- cmd/snapshot.go
- example/00-backup-restore-server-config.yaml
- pkg/compressor/compressor.go
- pkg/compressor/init.go
- pkg/compressor/types.go
- pkg/initializer/validator/validator_suite_test.go
- pkg/server/backuprestoreserver.go
- pkg/server/init.go
- pkg/server/types.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_suite_test.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapshot/snapshotter/types.go
- pkg/snapstore/snapshot.go
- pkg/snapstore/types.go
This PR added the compression/decompression feature. So, it compress/decompress the snapshots(full as well as Incremental) before/after uploading/downloading to/from object store. 
It also supports the backward compatibility for restoring from non-compressed snapshots as well as when different compressionPolicy were used to take the snapshot.
Fixes #255 
```noteworthy user
Add support for snapshot compression/decompression. Compression and compression policy can be configured through flags:  `--compress-snapshots` and `--compression-policy` respectively. Supported compression policies currently are `gzip` (default), `lzw` and `zlib`. Snapshot compression is …
```
> Compress the snapshots(full as well as Incremental) before uploading to object store and decompress the snapshot before restoration.

- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
It updates the helm-charts for [etcdbr-compression feature](https://github.com/gardener/etcd-backup-restore/pull/293).
Fixes #
```improvement operator
etcdbr-compression specification can be configured through helm-charts.
```
> Update the helm charts for etcdbr-compression feature.

- pkg/server/backuprestoreserver.go
Fixed an issue with backup-restore-server when it tries to take 2 full snapshots on starting of a fresh etcd-backup-restore.
Fixes #313 
```improvement operator
NONE
```
> Fixed an issue when fresh etcd-backup-restore tries to take 2 full snapshot.

- .ci/pipeline_definitions
prepares switch to kaniko-builder
> depend on publish-trait rather than injected step(s)

- chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- example/00-backup-restore-server-config.yaml
- pkg/snapshot/restorer/init.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/restorer/types.go
Introduce the auto-compaction-mode and auto-compaction-retention CLI flags for embedded ETCD to use auto-compaction during restoration.
Updated the helm-charts to run auto-compaction on Etcd as well as on embedded-Etcd of etcd-backup-restore sidecar.
Fixes  # [136](https://github.com/gardener/etcd-druid/issues/136) (Partially)
```improvement user
Added CLI flags `--auto-compaction-mode` and `--auto-compaction-retention` to configure auto-compaction for embedded etcd. Default values: auto-compaction-mode="periodic" and auto-compaction-retention="30m"
```
> Added Auto-Compaction for embedded Etcd and Update helm-charts to run auto-compaction on Etcd.

- .gitignore
- pkg/metrics/metrics.go
- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/garbagecollector.go
Adding a new metric `etcdbr_snapshotter_failure` used as a blanket metric to capture any snapshotter error. This will be used to add an alert to the gardener prometheus dashboard to alert the DoD of any backup sidecar error wrt any snapshotter operation failure.
This is a precursor to allowing etcd to serve traffic when the backup sidecar is starting up/restarting 
Fixes partially #325 
```improvement operator
Added a new metric `etcdbr_snapshotter_failure` used as a blanket metric to capture any snapshotter error. 
```
> Added new metric to capture any snapshotter error

- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/swift_snapstore.go
Updated the total number of chunks to one less than the maximum permitted value by each backup provider so that the number never goes beyond the permitted value.
Fixes https://github.tools.sap/kubernetes-canary/issues-canary/issues/817
Hotfix to ETCD backup restore version 0.12.0
```improvement operator
Updated number of chunks while uploading to never exceed the cloud provider limits.
```
> Updated number of chunks while uploading to never exceed the cloud provider limits.

- .ci/pipeline_definitions
Use testmachinery base image for integration_tests
Fix the integration tests pipeline step.
```
Traceback (most recent call last):
File "/cc/utils/cli.py", line 230, in <module>
main()
File "/cc/utils/cli.py", line 99, in main
parsed.func(parsed)
File "/cc/utils/cli.py", line 219, in function_runner
function(*function_args)
File "/cc/utils/cli/gardener_ci/config.py", line 54, in attribute
raw = _retrieve_model_element(cfg_type=cfg_type, cfg_name=cfg_name).raw
File "/cc/utils/cli/gardener_ci/config.py", line 25, in _retrieve_model_element
cfg_factory = ctx().cfg_factory()
File "/usr/local/lib/python3.8/dist-packages/ctx.py", line 183, in cfg_factory
factory = _cfg_factory_from_secrets_server()
File …
```
> Use testmachinery base image for integration_tests

- .ci/pipeline_definitions
- doc/usage/generating_ssl_certificates.md
This PR cleans up the pipeline definitions by introducing yaml anchors for the `tm_test` step to avoid redundancy.
Fixes #
```improvement operator
NONE
```
> Cleanup pipeline definitions

- .ci/integration_test
- .ci/tm-tests-playground
- testmachinery/testruns/etcd/templates/testrun.yaml
- testmachinery/testruns/etcd/values.yaml
This PR changes the infra secrets used for TM tests to the default CC secrets, due to recent permission-related changes to TM secrets.
Fixes #
```improvement operator
NONE
```
> Fix TM test infra credential fetching

- pkg/miscellaneous/miscellaneous.go
- pkg/snapshot/restorer/restorer_test.go
- test/utils/utils.go
Set the auto-compaction fields for Embedded-Etcd which were somehow got removed  in this  [commit](https://github.com/gardener/etcd-backup-restore/commit/1134755c1a5ca0626b2e9815e796b6d107c74fe8#diff-9547d8cc0c155be97c8e3a057b9351b6bf83108543f957fb8bac1adf111ccfaaL353-L354) of this [PR](https://github.com/gardener/etcd-backup-restore/pull/301). I think it happened while moving [StartEmbeddedEtcd](https://github.com/gardener/etcd-backup-restore/commit/1134755c1a5ca0626b2e9815e796b6d107c74fe8#diff-d67a01c5aa3ff7bb12c7e9945be604ac31bd8a766f5962760de4d8223e639aedR65-R99) to a different [package](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/miscellaneous/miscellaneous.go).
Fixes #
**Special notes for …
> Set the auto-compaction fields for Embedded-Etcd.

- pkg/defragmentor/defrag_test.go
- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR fixes a memory leak in the etcd probe loop resulting from not closing the etcd client in the `probeEtcd` function. Also close unclosed etcd clients in other parts of the code.
Fixes #
```improvement operator
NONE
```
> Close etcd clients to fix potential memory leaks

- cmd/compact.go
Rebased cherry-pick of https://github.com/gardener/etcd-backup-restore/pull/355
Fixes #
```improvement user
Compaction job will now throw warning instead of error if revisions are already compacted
```
> Updated compact subcommand to throw warning instead of error if revisions are already compacted

- doc/usage/getting_started.md
Fix command parameters **endpoints** in getting started documents.
When I tried the `snapshot` command, it showed the error message "Error: unknown flag: --etcd-endpoints". I checked the code and tested it, the flag should be `--endpoints`. 
NONE.
```improvement operator
NONE
```
> Fix endpoints parameters in document

- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
So far, users are provided with `--data-dir` flag for compaction subcommand but that was not really propagated to compaction as it was using it was setting it's own data-dir [https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/compactor/compactor.go#L70](https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/compactor/compactor.go#L70)
This PR propagates the options provided through `--data-dir` flag and propagate to compaction.
Fixes #
```improvement operator
```
> Propagated data directory from user flags to compaction.

- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- cmd/compact.go
- cmd/options.go
- example/00-backup-restore-server-config.yaml
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/defragmentor/defrag.go
- pkg/defragmentor/defrag_test.go
- pkg/etcdutil/init.go
- pkg/etcdutil/types.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/types/compactor.go
As FullSnapshot can be very large, so to avoid timeout in `context.WithTimeout()` and to configure a longer context timeout we have Introduced `--etcd-snapshot-timeout`  CLI flag in both `server` subcommand and in `compact` subcommand to take large etcd FullSnapshots and to take large compacted FullSnapshots, respectively.
As Etcd Defragmentation call can also be time taking for big `Etcd`, so to avoid timeout in `context.WithTimeout()` and to configure a longer context timeout we have Introduced `--etcd-defrag-timeout` CLI flags in both `server` subcommand and in `compact` subcommand for etcd defrag call.
Fixes #360 
Fixes #366 
Default values for all the flags are set to `8m`. …
> Mitigate timeout while taking FullSnapshot and while etcd defrag call

- pkg/snapstore/abs_snapstore.go
This a PR fixes a potential bug that may create wrong prefix in Azure backup storage for ETCD.
With v2 directory structure introduced with Compaction [PR](https://github.com/gardener/etcd-backup-restore/pull/301), it was observed that the blobName comes with the prefix concatenated to it. So if store prefix is set with `--store-prefix=prefix` then the blobName would be prefix/Name and with that Join prefix/prefix/Name, which points to a snapshot that does not exists. This PR resolves this bug.
Fixes #
```improvement operator
```
> Handled properly potential of wrong prefix formation in Azure.

- pkg/snapshot/snapshotter/snapshotter.go
There is a bug in compaction PR. When you upgrade the garden cluster from older ETCDBR image to new ETCD image that has compaction PR and folder structure change, delta snapshots are still saved in older directories. This PR fixed the bug so that delta snapshots are saved only under `v2` prefix.
Fixes #
```improvement operator
```
> Fixed a bug that was creating a different directory for delta snapshots.

- pkg/etcdutil/client/types.go
- pkg/etcdutil/etcdutil.go
[Some](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/etcdutil/etcdutil.go#L91) [functions](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/etcdutil/etcdutil.go#L122) in the `etcdutil` package will have to start using the `etcdutil/client`'s `Factory` interface introduced in #374. This might lead to circular imports because `etcdutil/client` already imports `etcdutil` for the `factoryImpl` struct.
This PR moves the `factoryImpl` implementation to the `etcdutil` package so that `etcdutil/client` no longer needs to import `etcdutil`, thus avoiding the potential circular imports.
Fixes #
Credits: @ishan16696 for pointing out this problem.
**Release …
> Moved client factory implementation to etcdutil to avoid potential cyclic imports later.

- cmd/copy.go
- cmd/options.go
- cmd/root.go
- doc/usage/getting_started.md
- go.mod
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_suite_test.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/snapshot/copier/copier.go
- pkg/snapshot/copier/copier_suite_test.go
- pkg/snapshot/copier/copier_test.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/ecs_s3_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/local_snapstore.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/utils.go
- pkg/types/snapstore.go
- vendor/modules.txt
1. Additional command `copy` is added with the following syntax and parameters. This command can copy data between two buckets.
`$ etcdbrctl copy [flags]`
>    --max-parallel-chunk-uploads uint   maximum number of parallel chunk uploads allowed  (default 5)
--snapstore-temp-directory string   temporary directory for processing (default "/tmp")
--source-storage-provider string    source snapshot storage provider
--source-store-container string     source container which will be used as snapstore
--source-store-prefix string        source prefix or directory inside container under which snapstore is created
--storage-provider string           snapshot storage provider
--store-container string            container which will be used as snapstore …
> Adding copy operation and additional authentication parameters forsource and target

- .ci/integration_test
- Makefile
Improves the integration tests in the following way:
* Ensures the integration tests can be executed locally by adding proper support for Darwin and using the existing credentials in the `$HOME/.aws` directory if the directory exists.
* If the tests fail, outputs the `etcdbrctl` logs.
Fixes #
While working on #383, I had some failing integration tests, but it was very difficult to tell the reason for the failures. It took me some time to adapt the `integration_test` script to be able to execute them locally, but even then I had no clue because they just passed. I had to add the `etcdbrctl` logs to the test output in order to be able to understand and fix the issue.
To run the …
> Ensure integration tests can be executed locally

- pkg/snapshot/snapshotter/snapshotter.go
This PR fixes a bug that sees the `leaseUpdateCtx` being created multiple times without being cancelled. This causes a memory leak without the contexts being cancelled
Fixes #
```improvement operator
Took care of a bug where contexts were created multiple times without being cancelled
```
> [Bug] Moved leaseUpdateCtx to not create the context multiple times

- pkg/snapshot/snapshotter/snapshotter.go
This PR fixes a bug that sees the `leaseUpdateCtx` being created multiple times without being cancelled. This causes a memory leak without the contexts being cancelled
Fixes #
```improvement operator
Took care of a bug where contexts were created multiple times without being cancelled
```
> Moved leaseUpdateCtx to not create the context multiple times

- .ci/integration_test
- .ci/unit_test
Recently, ginkgo released a new version `v2.0.0`. Our ci tests currently fetch ginkgo's master branch to run our ci tests and this has a few regressions with the new version.
This PR allows for a fixed version `v1.14.1` to be fetched so that our ci tests can run.
Fixes #
This PR is meant as a temporary measure so that our current work isn't blocked. I will in the meantime also work to migrate all our tests to ginkgo `v2.0.0`
```improvement operator
```
> Updated ci tests to use ginkgo 1.14.1 when running tests

- pkg/leaderelection/leaderelection.go
The current verbosity level of this log line is `Info`, which puts it on the same level as logs for snapshots being saved, garbage collection running, etc., however, this particular line is called on every leadership status check, which makes the logs incredibly chatty:
```
time="2022-02-01T16:00:31Z" level=info msg="Setting status to : 200" actor=backup-restore-server
time="2022-02-01T16:00:31Z" level=info msg="Starting snapshotter..." actor=backup-restore-server
time="2022-02-01T16:00:31Z" level=info msg="Will take next full snapshot at time: 2022-02-01 17:00:00 +0000 UTC" actor=snapshotter
time="2022-02-01T16:00:36Z" level=info msg="checking the leadershipStatus..." actor=leader-elector
time="2022-02-01T16:00:41Z" level=info msg="checking the …
```
> Reduce verbosity of leadershipStatus check log

- go.mod
- go.sum
Upgrade the `etcd-backup-restore` from using Go v1.14 to Go v1.16
Fixes #404 
```improvement operator
Upgrade the Go from v1.14 to v1.16
```
> Upgrade the Go from v1.14 to v1.16.

- pkg/health/heartbeat/heartbeat.go
- pkg/health/heartbeat/heartbeat_test.go
Currently snapshot lease updates are optimised in such a way that if revisions are not updated, the lease will not be renewed.
Going forward, the snapshot leases will be used as a heartbeat and so it would be desirable to renew them even if revisions have not been updated.
This PR does just that. It allows that heartbeat package to renew snapshot leases even if revisions are not updated
Fixes #
~~This PR is based on #406, hence lease ignore [`4a9496e`](https://github.com/gardener/etcd-backup-restore/commit/4a9496ee38a066f2714426e0ba17213fb44b03e7) and [`1fe44c5`](https://github.com/gardener/etcd-backup-restore/commit/1fe44c562c0d9d13ac7b3e484b24a82979f59304).~~
Reworked this PR …
> Renew snapshot leases even if snapshot skipped

- .ci/pipeline_definitions
- .ci/tm-tests-playground
- update pipeline definition to mount respective landscape repo
- update tm script to deploy testruns to a dedicated namespace and use a `tokenFile` at runtime.
- update pipeline to use `stable` tag instead of pinned (and slightly outdated) version
Fixes #
`TESTRUNNER_GARDEN_CLUSTER` is required to fetch flavor-relevant information.
```improvement operator
NONE
```
> update tm scripts

- pkg/miscellaneous/miscellaneous.go
Instead of returning a new error, we should return the original one to not cover important information that can help to solve the issue.
```improvement operator
NONE
```
> Don't hide error when creating K8s client

- main.go
The changes in here allow etcd-backup-restore to exit cleanly (cancel all contexts, stop leaderelection) when it's running inside a Kubernetes cluster, and the container receives a SIGTERM when the Pod is terminating.
I kept the SIGINT signal, since previously it caught it as well (via `os.Interrupt`). More information: https://pkg.go.dev/os/signal
I tested this by running etcd-backup-restore standalone and sending it SIGINT and SIGTERM signals:
```
pkill --signal SIGTERM <PROCESS NAME>
```
```improvement operator
Fixed etcd-backup-restore exiting immediately on SIGTERM without proper context cancellation
```
> Handle SIGTERM in main signal handler

- pkg/leaderelection/leaderelection.go
Reduces the amount of logs when running etcd-backup-restore as a Follower in a multi-instance etcd configuration:
```
time="2022-02-21T16:39:47Z" level=info msg="backup-restore currentState: Follower" actor=leader-elector
time="2022-02-21T16:39:52Z" level=info msg="backup-restore currentState: Follower" actor=leader-elector
time="2022-02-21T16:39:57Z" level=info msg="backup-restore currentState: Follower" actor=leader-elector
time="2022-02-21T16:40:02Z" level=info msg="backup-restore currentState: Follower" actor=leader-elector
time="2022-02-21T16:40:07Z" level=info msg="backup-restore currentState: Follower" actor=leader-elector
```
Fixes very verbose logs on non-leader etcd-backup-restore.
**Special notes for your …
> Reduce verbosity of leader current state log

- doc/usage/getting_started.md
- pkg/snapstore/s3_snapstore.go
Adds the capability to specify a different S3 endpoint within the S3 snapstore logic. This allows usage of etcd-backup-restore with non-AWS S3-compliant providers, such as [min.io](https://min.io/) or [Linode Object Storage](https://www.linode.com/products/object-storage/). It also adds a way of setting `S3ForcePathStyle`, which is needed for etcd-backup-restore to be able to save the snapshot in these S3-compatible providers. 
Note that by default when using the AWS SDK client, providing an empty string in the Endpoint field of the `aws.Config{}` struct is functionally similar to what was being done before (which was keeping it nil), and will generate the default endpoint, see: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.22.0/aws?utm_source=gopl …
> Add support for custom endpoints in S3 snapstore

- example/storage-provider-secrets/01-aws-s3-storage-secret.yaml
- pkg/snapstore/s3_snapstore.go
This PR adds support for S3 compatible providers (see #431) when configuration is passed via secrets.
```improvement operator
None
```
> Add feature parity for s3 compliant providers

- pkg/common/checkeractionwatchdog.go
- pkg/common/checkeractionwatchdog_test.go
- pkg/common/ownerchecker.go
- pkg/server/backuprestoreserver.go
Don't set the [HTTP  handler status to StatusServiceUnavailable](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/server/backuprestoreserver.go#L267) when the ownercheck's [DNS resolve lookup](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/common/ownerchecker.go#L59) fails.
Set the [HTTP  handler status to StatusServiceUnavailable](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/server/backuprestoreserver.go#L267) only when  [OwnerCheck](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/common/ownerchecker.go#L43) confirms that the current ownership has …
> Don't fail the Ownercheck when DNS resolve lookup fails.

- pkg/etcdutil/etcdutil.go
- pkg/types/compactor.go
- pkg/types/etcdconnection.go
1. Log the time taken by [compression](https://github.com/gardener/etcd-backup-restore/blob/1e3169cd7b7ea8d482f95ecd5fc4e23a6aed92e5/pkg/etcdutil/etcdutil.go#L258) to compress the full snapshot.
2. Log the time taken by [full snapshot api call](https://github.com/gardener/etcd-backup-restore/blob/1e3169cd7b7ea8d482f95ecd5fc4e23a6aed92e5/pkg/etcdutil/etcdutil.go#L251)
3. Increase the default snapshot time taken.
Fixes #454 
```improvement operator
NONE
```
> To capture the Full snapshot time taken and compression time taken

- Makefile
- pkg/server/httpAPI.go
This PR sets up an http endpoint with the path `/config` that actually downloads etcd config file from the backup restore sidecar based on the ETCD nodes.
Fixes part of #322
```improvement operator
```
> Introduced  endpoint in http server for  backup restorer.

- pkg/health/heartbeat/heartbeat.go
Reduces the amount of logs when running `etcd-backup-restore`. Also removed the time from the log as time is already there.
```
time="2022-03-31T14:24:52Z" level=info msg="Renewed member lease for etcd at 2022-03-31 14:24:52.244446329 +0000 UTC m=+494.963656744" actor=heartbeat
time="2022-03-31T14:25:02Z" level=info msg="Renewed member lease for etcd at 2022-03-31 14:25:02.299752615 +0000 UTC m=+505.018963027" actor=heartbeat
time="2022-03-31T14:25:12Z" level=info msg="Renewed member lease for etcd at 2022-03-31 14:25:12.353494461 +0000 UTC m=+515.072704874" actor=heartbeat
```
Fixes #
cc @aaronfern 
```improvement operator
NONE
```
> Reduce verbosity of Renew member lease log.

- pkg/miscellaneous/miscellaneous.go
Fix defragmentation fail issue which occurs due certificate IP SANs for single node etcd.
Fixes [#325](https://github.com/gardener/etcd-druid/issues/325) of etcd-druid.
```bugfix operator
Fix defragmentation fail issue which occurs due to x509: failed to validate certificate for 0.0.0.0 because it doesn't contain any IP SANs.
```
> Fix defragmentation fail issue which occurs due certificate IP SANs for single node etcd.

- pkg/health/heartbeat/heartbeat.go
Reduces the amount of logs when running `etcd-backup-restore`. Also removed the time from the log as time is already there.
```
time="2022-03-31T14:24:52Z" level=info msg="Renewed member lease for etcd at 2022-03-31 14:24:52.244446329 +0000 UTC m=+494.963656744" actor=heartbeat
time="2022-03-31T14:25:02Z" level=info msg="Renewed member lease for etcd at 2022-03-31 14:25:02.299752615 +0000 UTC m=+505.018963027" actor=heartbeat
time="2022-03-31T14:25:12Z" level=info msg="Renewed member lease for etcd at 2022-03-31 14:25:12.353494461 +0000 UTC m=+515.072704874" actor=heartbeat
```
Fixes #
cc @aaronfern 
```improvement operator
NONE
```
> Reduce verbosity of Renew member lease logs.

- doc/usage/getting_started.md
- example/storage-provider-secrets/05-openshift-container-storage-secret.yaml
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/utils.go
**What this PR does / why we need it**
OCS S3 snapstore now supports the new way of supplying access information via a secret mounted to a specific directory.
This allows for copying ETCd backups between OCS buckets with etcd-druid.
```improvement operator
OCS S3 Snapstore now supports supplying access information via a mounted secret.
```
> OCS S3 Snapstore support access information via mounted secret

- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/datavalidator_test.go
- pkg/initializer/validator/types.go
This PR checks whether wrong volume is mounted to ETCD container and if so, it doesn't start the ETCD. It writes shoot identifier to a file in the mounted volume. Then it checks if the mounted volume contains file with the same shoot identifier that is passed to it as POD Namespace.
Fixes #
https://github.com/gardener/etcd-backup-restore/issues/466
```improvement operator
- ETCD won't restart from the PVC if it is wrongly mounted to the pod
```
> Added a file containing shoot identifier to safe guard against wrong volume mount.

- pkg/health/heartbeat/heartbeat.go
- pkg/server/backuprestoreserver.go
It has been observed that etcdbr in etcd-events pod got stuck with this last error log:
```
2022-04-14 21:05:16 | {"log":"failed to create clientset: Get \"https://api.gcp-us1.garden.internal.canary.k8s.ondemand.com:443/api?timeout=32s\": dial tcp: lookup api.gcp-us1.garden.internal.canary.k8s.ondemand.com on 10.243.0.10:53: read udp 10.243.131.151:50810-\u003e10.243.0.10:53: i/o timeout","severity":"ERR"}
```
so, I think it should’ve return throw `Fatal error` to avoid potential deadlock condition.
Fixes #
```bugfix operator
Throw Fatal error to avoid edge case potential deadlocks.
```
> Throw Fatal error to avoid potential deadlock condition.

- pkg/health/heartbeat/heartbeat.go
- pkg/health/heartbeat/heartbeat_suite_test.go
- pkg/health/heartbeat/heartbeat_test.go
- pkg/server/backuprestoreserver.go
It has been observed that etcdbr in etcd-events pod got stuck with this last error log:
```
2022-04-14 21:05:16 | {"log":"failed to create clientset: Get \"https://api.gcp-us1.garden.internal.canary.k8s.ondemand.com:443/api?timeout=32s\": dial tcp: lookup api.gcp-us1.garden.internal.canary.k8s.ondemand.com on 10.243.0.10:53: read udp 10.243.131.151:50810-\u003e10.243.0.10:53: i/o timeout","severity":"ERR"}
```
so, I think it should’ve return throw `Fatal error` to avoid potential deadlock condition.
Fixes #
```bugfix operator
Throw Fatal error to avoid edge case potential deadlocks.
```
> Throw Fatal error to avoid potential deadlock.

- pkg/snapstore/swift_snapstore.go
Fixes the retrieval of credentials when using the copy operation with the `Swift` snapstore.
Without this fix we get the following error when trying to copy backups:
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
A future release of golang/protobuf will delete this package,
which has long been excluded from the compatibility promise.
time="2022-05-06T10:29:51Z" level=info msg="etcd-backup-restore Version: v0.15.2"
time="2022-05-06T10:29:51Z" level=info msg="Git SHA: c9b5c3d0"
time="2022-05-06T10:29:51Z" level=info msg="Go Version: go1.17.9"
time="2022-05-06T10:29:51Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-05-06T10:29:51Z" level=fatal msg="Could not get source and destination snapstores: could …
```
> Fixes copy operation for Swift snapstore

- pkg/server/backuprestoreserver.go
This PR slightly changes when the `etcd` process is killed if the owner check fails so that the connection from the `kube-apiserver` to the `etcd` is broken. 
Previously a corner case could happen which would leave `etcd` running and therefore the shoot's control plane would not get properly shut down in the source seed during control plane migration leading to split brain scenario:
This corner case can happen in the following scneario (but is probably not limited only to it)
1. If the backup bucket is not reachable for any reason `backup-restore` will fail to create a snapshot
2. backup-restore constantly loops trying to start the `snapshotter`
3. Control plane migration is triggered and eventually owner is changed during the restore phase.
4. …
> Kill etcd process exactly before taking a final snapshot

- pkg/server/backuprestoreserver.go
Cherry-pick of PR: https://github.com/gardener/etcd-backup-restore/pull/478
Fixes #
cc @plkokanov 
```improvement operator github.com/gardener/etcd-backup-restore #478 @plkokanov 
When the owner check fails, `etcd-backup-restore` will restart the `etcd` process right before attempting to take a final snapshot, if the owner check was previously successful.
```
> [cherry-pick of #478 ]Kill etcd process exactly before taking a final snapshot

- pkg/snapstore/s3_snapstore.go
This PR adds support for S3 compatible providers (see #431) when configuration is passed via secrets mounts which was somehow missed by this PR https://github.com/gardener/etcd-backup-restore/pull/446
Fixes #
```improvement operator
NONE
```
> Add feature parity for s3 compliant providers.

- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/types.go
Till now to verify `boltDB`, backup-restore used to open it and while opening `boltDB` when it was unable to acquire the lock over database file then backup-restore used to ends up waiting indefinitely for other process to release the lock over database file.
This PR mitigate this issue by introducing a timeout setting to open boltDB, so backup-restore won't have to wait indefinitely, if it fails to acquire lock it can throw error after timeout occurs.
**Note**: Till now we haven’t decided what action needs to be taken when backup-restore throws error in this case but I think `etcd-druid` can take care of this case as it seems to be just like restoration of single member in `multi-node etcd`.
Fixes  # …
> Added a timer while opening a boltDB and improve error handling for verifying database.

- .ci/integration_test
- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/types.go
- pkg/server/backuprestoreserver.go
- pkg/types/restorer.go
- test/e2e/integration/cloud_backup_test.go
If a node abruptly shutdown in ETCD multi node cluster, it checks revision before coming back up. If the revision number is lesser than the latest snapshot, it fails to restore. Whereas this check is necessary for a single node cluster, it's not necessary for a multinode setup. This PR takes care of both type of clusters.
Fixes #481 
```noteworthy operator
- An initial-cluster field is now expected in the ETCD config
```
> Added logic for single node restoration after abrupt shutdown.

- .ci/build
- .ci/pipeline_definitions
- Makefile
- build/Dockerfile
This PR lets the CI pipeline build multi-arch images including `linux/amd64` and `linux/arm64` images.
Fixes partly #https://github.com/gardener/gardener/issues/6258
```noteworthy operator
Published docker images for Etcd-Backup-Restore are now multi-arch ready. They support `linux/amd64` and `linux/arm64`.
```
```noteworthy operator
The Etcd-Backup-Restore image has been updated to `Alpine 3.15.4`.
```
> Build Multi-Arch Images 📦 

- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/types.go
- pkg/member/member_control.go
- pkg/member/member_control_test.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/server/httpAPI.go
By not letting it trigger the the restoration this PR fixes the issues of wrong restoration of single member in a multi-node etcd cluster in case of data-dir found to be invalid. Please refer [here](https://github.com/gardener/etcd-druid/issues/361#issuecomment-1174907483).
This PR also fixes one bug in Scale feature in func: [IsMemberInCluster](https://github.com/gardener/etcd-backup-restore/blob/a6ee3fd56bc0401fe54f048fe8166750f677a777/pkg/member/member_control.go#L164) as it shouldn't return the error, it should return the nil.
Fixes https://github.com/gardener/etcd-druid/issues/361 (Temporary fix)
```bugFix operator
Temp fix: skip the single member …
```
> Temp fix: skip single member restoration in case of data-dir invalid.

- cmd/restore.go
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/initializer/initializer.go
- pkg/member/member_control.go
- pkg/server/backuprestoreserver.go
- pkg/server/httpAPI.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
When we create a new etcd cluster(size=1) then Peer address is correct, but after restoration of Etcd by backup-restore the Peer Address is not seems to be correct. This PR fixes this bug.
Fixes #500 
Please test Scale up feature only after this [PR](https://github.com/gardener/etcd-backup-restore/pull/501) get merge as it contains one fix of Scale up feature.
```improvement operator
Assigned the correct Peer address to the Etcd after it restores from backup-bucket.
```
> Assigned the correct Peer Address to Etcd after it restores from the backup-bucket.

- pkg/member/member_control.go
- pkg/snapshot/restorer/restorer.go
This PR updates member promote logic to not attempt to update peer URL while promoting a member.
Promote member is called only when in multi node case and in that case updated member peer URLs are already used since these are new nodes/pods trying to join the cluster
Fixes #
```improvement operator
No attempt is made to update member Peer URL when trying to promote a member
```
> Don't update peer URL when promoting member

- cmd/restore.go
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/types.go
- pkg/member/member_control.go
- pkg/member/member_control_test.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/server/backuprestoreserver.go
- pkg/server/httpAPI.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
Cherry pick [`40e936`](https://github.com/gardener/etcd-backup-restore/commit/40e9368d4df0785ff5713d0a9eb94d16343610e3), [`7d27a4`](https://github.com/gardener/etcd-backup-restore/commit/7d27a47f5793b0949492d225ada5fd8344b6b6a2), [`41f9c5`](https://github.com/gardener/etcd-backup-restore/commit/41f9c5215aa1c99cd8ed5ccecc281d755882d45b), and [`008a47`](https://github.com/gardener/etcd-backup-restore/commit/008a478e4a43c3d47f2dac721623861059fca78f) onto `rel-v0.18` branch
Fixes gardener/etcd-druid #361 (temporary fix), and #500 
```improvement operator https://github.com/gardener/etcd-backup-restore #504 @aaronfern 
Fixed a bug where etcd calls related to multi …
```
> Cherry pick changes for rel v0.18.1

- doc/usage/getting_started.md
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/swift_snapstore.go
This PR drops the feature of passing storage container secrets through ENV for the following storage provider:
1. AWS: S3
2. Openstack: Swift
3. Openshift: OCS
4. Azure: ABS
5. AliCloud: OSS
Fixes #
```breaking operator
Dropping the feature of passing storage container credentials through ENV for the following storage provider: S3, Swift, OCS, ABS, OSS. Please switch to pass the storage container credentials through volume file mount. 
```
> Drop the feature of passing storage container secrets through Environment Variable.

- pkg/miscellaneous/miscellaneous.go
This PR fixes an issue where the wrong endpoint is used to talk to the etcd cluster.
Fixes #
```improvement operator
An issue has been fixed that caused the `Backup-Restore` component to connect to the wrong etcd cluster for initializing and member-add procedures.
```
> Fix svc endpoint extraction

- pkg/miscellaneous/miscellaneous.go
Cherry pick [`6c8708`](https://github.com/gardener/etcd-backup-restore/pull/510/commits/6c870892e2c256c7cdaa382fd46618c5c34a3d49) on branch `rel-v0.18`
Fixes #
```improvement operator github.com/gardener/etcd-backup-restore #510 @timuthy 
An issue has been fixed that caused the `Backup-Restore` component to connect to the wrong etcd cluster for initializing and member-add procedures.
```
> Cherry pick changes for rel v0.18.2

- pkg/etcdutil/client/option.go
- pkg/etcdutil/etcdutil.go
- pkg/member/member_control.go
- pkg/miscellaneous/miscellaneous.go
- pkg/server/httpAPI.go
- pkg/types/etcdconnection.go
- pkg/types/restorer.go
This PR adds a new flag `--service-endpoints` to the `etcdbrctl server` command. These (Kubernetes) service URLs ensure that `etcd-backup-restore` only connects to etcd member which are ready to server traffic. Especially the `MemberAdd` and `Init` steps require this.
/cc @aaronfern 
```improvement operator
A new flag `--service-endpoints` has been added to the `etcdbrctl server` command. These (Kubernetes) service URLs ensure that `etcd-backup-restore` only connects to etcd member which are ready to server traffic. Especially the `MemberAdd` and `Init` steps require this.
```
> [rel-v0.18] Add serviceEndpoint to connect to etcd

- pkg/errors/error.go
- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/types.go
- pkg/leaderelection/leaderelection.go
- pkg/leaderelection/leaderelection_test.go
- pkg/member/member_control.go
- pkg/member/member_control_test.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/server/backuprestoreserver.go
- pkg/server/httpAPI.go
- pkg/types/leaderelection.go
This PR adds a feature for restoration of single member in mult-node etcd cluster in case of data/data-dir of etcd member found to be corrupt/invalid.
Fixes  https://github.com/gardener/etcd-druid/issues/368
Design Doc PR: https://github.com/gardener/etcd-druid/pull/376
```noteworthy user
For multi-node etcd: Added a feature of single member etcd restoration in case of data/data-dir of etcd member found to be corrupted or invalid.
```
> Adds a feature of single member restoration in multi-node etcd.

- pkg/etcdutil/client/option.go
- pkg/etcdutil/etcdutil.go
- pkg/member/member_control.go
- pkg/miscellaneous/miscellaneous.go
- pkg/server/httpAPI.go
- pkg/types/etcdconnection.go
- pkg/types/restorer.go
This PR adds a new flag `--service-endpoints` to the `etcdbrctl server` command. These (Kubernetes) service URLs ensure that `etcd-backup-restore` only connects to etcd member which are ready to server traffic. Especially the `MemberAdd` and `Init` steps require this.
/cc @aaronfern 
```improvement operator
A new flag `--service-endpoints` has been added to the `etcdbrctl server` command. These (Kubernetes) service URLs ensure that `etcd-backup-restore` only connects to etcd member which are ready to server traffic. Especially the `MemberAdd` and `Init` steps require this.
```
> Add serviceEndpoint to connect to etcd

- build/Dockerfile
This PR upgrades the alpine image used to build `backup-restore` images
Fixes 
[CVE-2022-2068](https://nvd.nist.gov/vuln/detail/CVE-2022-2068)
[CVE-2022-2097](https://nvd.nist.gov/vuln/detail/CVE-2022-2097)
[CVE-2022-37434](https://nvd.nist.gov/vuln/detail/CVE-2022-37434)
```noteworthy operator
Base alpine image upgraded from `3.15.4` to `3.15.6`
```
> Upgrade alpine image used to build backup-restore image

- pkg/etcdutil/etcdutil.go
- pkg/initializer/initializer.go
- pkg/leaderelection/leaderelection.go
- pkg/member/member_control.go
- pkg/metrics/metrics.go
- pkg/miscellaneous/miscellaneous.go
- pkg/server/backuprestoreserver.go
This PR adds new metrics which required to be exposed via backup-restore to get more information about multi-node etcd which will be helpful in debugging/fine-tuning the multi-node etcd.
Fixes # https://github.com/gardener/etcd-druid/issues/358
Please see https://github.com/gardener/etcd-druid/pull/414
```improvement operator
Added new metrics for multi-node etcd: `etcdbr_defragmentation_duration_seconds`, `etcdbr_restoration_duration_seconds` , `etcdbr_cluster_size` , `etcdbr_is_learner `, `etcdbr_is_learner_count_total `, `etcdbr_add_learner_duration_seconds `, `etcdbr_member_remove_duration_seconds `, `etcdbr_member_promote_duration_seconds `.
```
> Added the new metrics needed to be exposed for multi-node etcd.

- pkg/initializer/validator/datavalidator.go
- pkg/initializer/validator/types.go
- pkg/initializer/validator/validator_suite_test.go
BoltDB is not expected a corrupt DB file as it contains the information of pages and other metadata information.
This PR handles the `boltDB panic` in case of database found to be corrupt while opening the database file during the data-dir verification by backup-restore.
Fixes #519 
/cc @shreyas-s-rao 
```improvement operator
Handles the bolt database panic in case of database found to be corrupt.
```
> Handling the boltDB panic in case of database found to be corrupt.

- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/types/leaderelection.go
We have observed that currently `ProbeEtcd` is using the longer timeout which is set using this flag `--etcd-connection-timeout` and in our landscapes `--etcd-connection-timeout` is set to `5mins`.  (check [here](https://github.com/gardener/etcd-druid/blob/master/pkg/component/etcd/statefulset/values_helper.go#L247))
Due to this longer Timeout `ProbeEtcd` is keep waiting instead of failing the probe and meanwhile when `ProbeEtcd` is waiting if corresponding etcd comes-up then `ProbeEtcd` get succeeds this might leads to some race-conditions between the go-routines as `ProbeEtcd` is suppose to fail.
This PR fixes this issue by using the shorter Timeout of `5sec` in `ProbeEtcd`.
Fixes #
**Special notes for your …
> Fix the ProbeEtcd timeout.

- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/server/backrestoreserver_test.go
- pkg/server/backuprestoreserver.go
- pkg/server/httpAPI.go
Member peer URL should always be updated. This will ensure that member peer URL is correct updated even if there was a recreation of sts and as a consequence a new configmap having a cluster size > 1 is available.
It also fixes the way we identify scale up scenario. 
Fixes #533 
```improvement operator
Always update member peer URL, changed the way scale-up of etcd cluster is identified.
```
> Member Peer URL not updated when scaled to multi-node, scale identification is also not correct

- .ci/integration_test
I was unable to run the integration tests locally as it was not getting the `REGION` ENV from file `${HOME}/.aws/config` which leads to the failure in creation of S3 bucket.
This PR fixes this issue to run the integration tests locally.
Fixes #
```improvement operator
None
```
> Fix the integration tests to run them locally.

- .ci/pipeline_definitions
- build/Dockerfile
This PR updated the golang version used to build images from `1.18.3` to `1.18.6`
This PR also updated the pipeline definitions to use go `1.18.6`
Fixes [CVE-2022-27664](https://nvd.nist.gov/vuln/detail/CVE-2022-27664)
```noteworthy operator
Updated golang version used to build images to 1.18.6
```
```noteworthy operator
Updated golang version to 1.18
```
> Update to golang 1.18.6

- .ci/pipeline_definitions
- build/Dockerfile
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/server/backrestoreserver_test.go
- pkg/server/backuprestoreserver.go
- pkg/server/httpAPI.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/types/leaderelection.go
This PR cherry picks commits for the following PRs
1. Fix the ProbeEtcd timeout. - https://github.com/gardener/etcd-backup-restore/pull/532
2. Member Peer URL not updated when scaled to multi-node, scale identification is also not correct - https://github.com/gardener/etcd-backup-restore/pull/534
3. Update to golang 1.18.6 - https://github.com/gardener/etcd-backup-restore/pull/535
Fixes #
```bugfix operator github.com/gardener/etcd-backup-restore #532 @ishan16696 
To avoid potential race-condition between go-routines updated `probeEtcd func()` to use shorter timeout.
```
```improvement operator github.com/gardener/etcd-backup-restore #534 @unmarshall 
Always …
```
> Cherry pick commits for branch rel-v0.20

- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
It has been have observed that there is no need to close the snapshotter in [OnStoppedLeading func(){....}](https://github.com/gardener/etcd-backup-restore/blob/ab224ee318896e90c72b4a6158844bc400feed9e/pkg/server/backuprestoreserver.go#L265-L273) as snapshotter will get close by [handleSsrStopRequest](https://github.com/gardener/etcd-backup-restore/blob/ab224ee318896e90c72b4a6158844bc400feed9e/pkg/server/backuprestoreserver.go#L599) whenever context get canceled due to loss of leadership. Although In [OnStoppedLeading](https://github.com/gardener/etcd-backup-restore/blob/ab224ee318896e90c72b4a6158844bc400feed9e/pkg/server/backuprestoreserver.go#L265-L273) we are taking the mutex lock before accessing the resource but still I would suggest it is …
> To decrease the likelihood of race condition while closing the snapshotter.

- pkg/server/backuprestoreserver.go
This PR updated the functionality of etcd member peer URL updation to only log an error in case of failure.
This is needed as sometimes etcd restoration takes longer to complete and etcd member peer URL updation failure will then cause the container to crash before the restoration can complete
Fixes #539 
```improvement operator
[bug-fix] backup-restore does not return error when it fails to update PeerURL of member.
```
> UpdateMemberPeerURL only logs an error in case of failure

- pkg/server/backuprestoreserver.go
Cherry pick [`685178`](https://github.com/gardener/etcd-backup-restore/pull/540/commits/685178e784e0bb12991df893d4f632ad1e14bfe9)
Fixes #
```improvement operator github.com/gardener/etcd-backup-restore #540 @aaronfern 
[bug-fix] backup-restore does not return error when it fails to update PeerURL of member.
```
> [rel-v0.20] UpdateMemberPeerURL only logs an error in case of failure

- pkg/server/httpAPI.go
It has been observed that whenever etcd goes down or restarted then [initialization](https://github.com/gardener/etcd-backup-restore/blob/bd4f088085e43aaa23101e1b98699a2b626532d1/pkg/server/httpAPI.go#L225) request closes the snapshotter but there is no need of that as snapshotter will get close by [handleSsrStopRequest](https://github.com/gardener/etcd-backup-restore/blob/bd4f088085e43aaa23101e1b98699a2b626532d1/pkg/server/backuprestoreserver.go#L593) if `backup-leader` moves to `UnkownState` and cancels the context as etcd is down.
This PR removes the closing of `snapshotter` during initialization phase to removes the redundancy of closing of snapshotter.
Fixes #
@unmarshall …
> Removes the closing of snapshotter during initialization.

- .ci/pipeline_definitions
- build/Dockerfile
This PR updated the golang version used to build images from `1.18.6` to `1.19.2`
This PR also updated the pipeline definitions to use go `1.19.2`
Fixes
[CVE-2022-2879](https://nvd.nist.gov/vuln/detail/CVE-2022-2879)
[CVE-2022-2880](https://nvd.nist.gov/vuln/detail/CVE-2022-2880)
[CVE-2022-41715](https://nvd.nist.gov/vuln/detail/CVE-2022-41715)
```noteworthy operator
Updated golang version used to build images to 1.19.2
```
> Update to golang 1.19.2

- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
This PR removes triggering the out-of-schedule full snapshot after defragmentation as triggering the out-of-schedule full snapshot and closing of snapshotter can cause potential deadlock situation.
temporary fixes: [issue: 553](https://github.com/gardener/etcd-backup-restore/issues/553)
```bugfix operator
To avoid race-condition between closing of snapshotter and taking snapshot after defrag, removing the out-of-schedule full snapshot triggered after defragmentation of etcd.
```
> Removes taking full snapshot after defragmentation to avoid race-condintion.

- CONTRIBUTING.md
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/abs_snapstore_test.go
- pkg/snapstore/ecs_s3_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/generic_s3_snapstore.go
- pkg/snapstore/init.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/types/snapstore.go
Addition of min-chunk-size flag, it allows to fine tune multi-part upload across different store providers
none
```improvement operator
making chunk-size configurable by introducing flag: `--min-chunk-size` (default value 5MB), it will be helpful in fine tuning the multi-part chunk upload size for different storage provider.
```
> [Feat] min-chunk-size flag

- pkg/server/backuprestoreserver.go
- pkg/server/types.go
This PR removes the dead code which was left while removing the ownercheck code. Please refer [here](https://github.com/gardener/etcd-backup-restore/pull/555#pullrequestreview-1205898995)
Fixes #
```improvement operator
None
```
> Removed unused code which was left while removing ownerCheck.

- example/storage-provider-secrets/02-openstack-swift-storage-secret.yaml
- pkg/snapstore/swift_snapstore.go
This PR adds support for passing [Application credentials](https://docs.openstack.org/keystone/latest/user/application_credentials.html) to authenticate Openstack.
This PR supports the backward compatibility, it doesn't removes the old way(username/password) of passing Openstack credentials.
Fixes #575 
```noteworthy operator
Added support for Application credentials to authenticate Openstack client for Openstack backup buckets.
```
> Added support for Application credentials to authenticate openstack.

- go.mod
- vendor/modules.txt
This change does not really change the `k8s.io/client-go` version as there is a replace directive to ping the dependency to v0.19.6:
https://github.com/gardener/etcd-backup-restore/blob/c12013e0773e0adc6264e15ecc752663a7195258/go.mod#L183-L201
Part of https://github.com/gardener/gardener/issues/6807
```improvement operator
NONE
```
> Update `k8s.io/client-go` to a human-readable version

- pkg/miscellaneous/miscellaneous.go
- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
This PR enhances the condition of checking whether to take a full snapshot or not during startup of backup-restore to avoid missing of any full-snapshot within 24hrs of window.
Fixes #570 
```improvement operator
Enhances the decision to take full snapshot during startup of etcd-backup-restore to avoid missing of any full-snapshot.
```
> Enhances the decision to take full snapshot during startup to avoid missing of any full-snapshot.

- .ci/pipeline_definitions
- build/Dockerfile
Updates golang to `1.19.5` and alpine to `3.15.7`.
Fixes #
```improvement user
Update alpine base image to `3.15.7`.
```
```noteworthy developer
Update golang build version to `1.19.5`.
```
> Update to golang 1.19.5, alpine 3.15.7

- pkg/server/backuprestoreserver.go
This PR fixes a bug when backup-restore fails to apply watch or fails to collect events if required revision has been compacted which will leads to snapshotter not getting restarted.
Bug is fixed when backup-restore fail take a initial delta snapshot then it is better trigger a full snapshot.
Fixes #599 
```bugfix operator
Fixes a bug in snapshotter loop when backup-restore fails to collect events or fails to apply watch if required etcd revision has been compacted.
```
> Take a full snapshot when backup-restore fails to apply watch if required revision has been compacted.

- pkg/server/backuprestoreserver.go
Cherry-pick of https://github.com/gardener/etcd-backup-restore/commit/b980beecb81485314c721500b3e51efefddc8af2
Fixes #
```bugfix operator
Fixes a bug in snapshotter loop when backup-restore fails to collect events or fails to apply watch if required etcd revision has been compacted.
```
> Cherry-pick of #PR600

- .ci/build
- Makefile
This is a cherry-pick of https://github.com/gardener/etcd-backup-restore/pull/475 due to failing CI job on that PR as the PR is quite old now.
These changes allow for flexibility to specify the VERSION and GIT_SHA using env vars. This is useful for other CI environments where e.g. `git` isn't present.
Fixes #
```improvement operator
Allow for flexible build opts for other CI tools.
```
> Allow for flexible build opts for other CI tools

- pkg/initializer/initializer.go
- pkg/member/member_control.go
- pkg/member/member_control_test.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
This PR improves the scale-up detection conditions to avoid potential failure while migrating single node etcd to multi-node etcd cluster.
Fixes #606 
```improvement operator
Enhances the scale-up detection conditions to avoid potential failure while from migrating single node etcd to multi-node etcd cluster.
```
> Enhancing the scale-up detection conditions.

- .ci/unit_test
- pkg/compactor/compactor.go
- pkg/compactor/compactor_suite_test.go
- pkg/compactor/compactor_test.go
- pkg/initializer/initializer.go
- pkg/initializer/validator/datavalidator.go
- pkg/miscellaneous/miscellaneous.go
- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_suite_test.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/restorer/types_test.go
- pkg/types/restorer.go
Fix cleanup of temporary directory used for restoration and improve and optimize restoration in general. As part of this task, this PR does the following:
Fixes #604 
/invite @unmarshall @aaronfern @ishan16696 
```improvement operator
Optimize disk usage during restoration of delta snapshots, and remove scope for errors in the process.
```
```improvement user
Introduce CLI flag `--restoration-temp-snapshots-dir` to configure directory used for temporarily persisting delta snapshots during restoration.
```
```improvement user
Fix behavior of `--data-dir` for `etcdbrctl compact` command to be consistent with the flag's usage in other `etcdbrctl` commands.
```
> Fix and optimize restoration of delta snapshots

- build/Dockerfile
Upgrade alpine base image version used from `v3.15.7` to `v3.15.8`
Fixes #
```improvement operator
Base alpine image upgraded from `3.15.7` to `3.15.8`
```
> Upgrade alpine base image to 3.15.8

- .ci/pipeline_definitions
- build/Dockerfile
- go.mod
This PR upgrades the golang runtime and build version to `go 1.20`.
/area quality
Fixes [critical vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2023-24537).
```improvement developer
Upgrade to go 1.20.3
```
> Upgrade to go 1.20.3

- pkg/member/member_control.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
As now we depends on annotation added by druid to [detect scale-up feature](https://github.com/gardener/etcd-backup-restore/blob/96e810ff6a431b74580a74932cb9736fcd7e2f67/pkg/initializer/initializer.go#L62) I noticed when a rolling update happens, this piece of code with sts status:
```go
if *curSts.Spec.Replicas > 1 && *curSts.Spec.Replicas > curSts.Status.UpdatedReplicas {
return pointer.StringPtr(ClusterStateExisting), nil
}
```
etcd statefulset status:
```
status:
availableReplicas: 2
collisionCount: 0
currentReplicas: 2
currentRevision: etcd-aws-78fcdddc48
observedGeneration: 4
readyReplicas: 2
replicas: 3
updateRevision: etcd-aws-5d4d79969b
updatedReplicas: 1
```
returns the cluster state of etcd as `existing` which gives backup-restore a false …
> Fix a bug which falsely detects scale-up scenario incase of rolling update of statefulset.

- pkg/compactor/compactor_suite_test.go
- pkg/defragmentor/defragmentor_suite_test.go
- pkg/health/heartbeat/heartbeat_suite_test.go
- pkg/initializer/validator/datavalidator_test.go
- pkg/initializer/validator/validator_suite_test.go
- pkg/member/member_control_suite_test.go
- pkg/member/member_control_test.go
- pkg/snapshot/copier/copier_suite_test.go
- pkg/snapshot/restorer/restorer_suite_test.go
- pkg/snapshot/restorer/restorer_test.go
- pkg/snapshot/snapshotter/snapshotter_suite_test.go
- test/utils/utils.go
This PR adds unit tests for func `IsClusterScaledUp`:
https://github.com/gardener/etcd-backup-restore/blob/281a6ca98d91a22d76fae9b4ebbf429a97cf7784/pkg/member/member_control.go#L319
Fixes #
```improvement operator
None
```
> Add unit tests for func IsClusterScaledUp.

- .ci/integration_test
/area backup
/area security
/area compliance
/kind task
/kind test
/platform aws
This PR configures the S3 buckets created by integration tests to be blocked from public access as per standard practices. This is achieved by putting a public-access-block on the created bucket, as per [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-public-access-block.html).
Fixes #
cc @vlerenc 
```improvement developer
Block public access for S3 buckets created by integration tests.
```
> Block public access to S3 bucket created by integration tests

- pkg/initializer/initializer.go
- pkg/member/member_control.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_suite_test.go
- pkg/miscellaneous/miscellaneous_test.go
If scale-up case is detected then better to add a learner with exponential backoff.
Fixes # https://github.com/gardener/etcd-backup-restore/pull/608#discussion_r1155803217
```improvement operator
Add a learner with backoff in case of scale-up feature is triggered.
```
> If scale-up is detected then add learner with backoff.

- pkg/member/member_control.go
- pkg/member/member_control_test.go
First, try to determine scale-up case by checking whether member is already part of cluster or not. In case of failure of api call then check for `ScaledToMultiNodeAnnotationKey` annotation in etcd statefulset. This will remove any case of false positive for scale-up scenario.
Fixes #623 and Fixes #622
```improvement operator
None
```
> Improve scale-up detection.

- build/Dockerfile
Bump alpine base version for Docker build to `3.18.2`, which includes fixes for CVEs [CVE-2023-1255](https://security.alpinelinux.org/vuln/CVE-2023-1255) and [CVE-2023-2650](https://security.alpinelinux.org/vuln/CVE-2023-2650).
Fixes #
/invite @aaronfern 
```improvement operator
Bump alpine base version for Docker build to `3.18.2`.
```
> Bump alpine base version for Docker build to 3.18.2

- .ci/pipeline_definitions
Add CVE categorization to etcd-backup-restore within the gardener context.
Fixes partially https://github.com/gardener/etcd-druid/issues/633
/invite @ashwani2k 
```improvement developer
Add CVE categorization for etcd-backup-restore.
```
> Add CVE categorization for etcd-backup-restore

- build/Dockerfile
- pkg/server/httpAPI.go
- pkg/snapstore/utils.go
This PR updates `etcd-backup-restore` to use distroless images and as a result updats file paths of files created by itself to use the user home directory
Fixes #635 
```noteworthy operator
Etcd-backup-restore now uses a distroless image as its base image. It is no longer compatible with [etcd-custom-image](https://github.com/gardener/etcd-custom-image), and must be used with [etcd-wrapper](https://github.com/gardener/etcd-wrapper) instead. 
```
```noteworthy operator
Etcd-backup-restore now uses the user home directory to create files.
```
> Use distroless images and use user home dir to create files

- doc/usage/garbage_collection.md
- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/types/snapshotter.go
This PR resolves the request for a configurable retention period for delta snapshots. This feature aims to provide users with more flexibility in preserving delta snapshots for both GC policies (`Exponential` and `Limit-Based`) 
- Added a new `delta-snapshot-retention-period` parameter in the `SnapshotterConfig` to allow for the customization of the retention period for delta snapshots. This new setting can be adjusted via command-line flags.
- Modified the `GarbageCollectDeltaSnapshots` function, formerly `garbageCollectDeltaSnapshots`, to utilize the `DeltaSnapshotRetentionPeriod` parameter when identifying delta snapshots for deletion. This change ensures that delta snapshots within the user-specified retention period will not be deleted.
- Added …
> Implement Configurable Retention Period for Delta Snapshots

- pkg/initializer/initializer.go
This PR enables the first member to skips the scale-up checks as first member of etcd cluster can never be part of scale-up(`1->3 replicas`). please check this: https://github.com/gardener/etcd-backup-restore/issues/646#issuecomment-1635716166
Fixes #646 
```improvement operator
While scaling up a non-HA etcd cluster to HA skipping the scale-up checks for first member of etcd cluster as first member can never be a part of scale-up scenarios.
```
> Skip scale-up checks for first member of etcd cluster.

- pkg/initializer/initializer.go
Cherry-pick of #649.
This PR enables the first member to skips the scale-up checks as first member of etcd cluster can never be part of scale-up(`1->3 replicas`). please check this: https://github.com/gardener/etcd-backup-restore/issues/646#issuecomment-1635716166.
Fixes #
```improvement operator
While scaling up a non-HA etcd cluster to HA skipping the scale-up checks for first member of etcd cluster as first member can never be a part of scale-up scenarios.
```
> Skip scale-up checks for first member of etcd cluster. (#649)

- pkg/server/httpAPI.go
This PR moves `ioutil` calls to `os pkg` as ioutil has been deprecated in Go 1.16.
Please see this: https://pkg.go.dev/io/ioutil
Fixes #
```improvement operator
None
```
> move ioutil func calls to different pkg as ioutil has been deprecated.

- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/types/compactor.go
This PR adds a provision of sleep duration  after the `Compact` function done with uploading snapshot. This sleep duration is needed as prometheus is required to collect necessary metrics for network activity after a fast full snapshot upload. The sleep duration is supplied as flag to `etcdbrctl compact` command and set to 0 by default. But the flag can be configured by any agent, who is using `etcdbrctl`, to set any duration value like 60s, 2m etc. `60s` value of sleep duration is enough to allow sufficient time for Prometheus to scrape network related metrics after a fast full snapshot upload.
Fixes #
https://github.com/gardener/etcd-druid/pull/648 …
> Adds sleep command at the end of compaction.

- example/01-etcd-config.yaml
This PR adds `etcd-config.yaml` file. It will be useful in running single member etcd and backup-restore locally for testing purposes. Just have to export ENV: `ETCD_CONF=example/00-etcd-config.yaml`
Fixes #
```improvement operator
NONE
```
> Add `example/etcd-config.yaml` to run backup-restore as a process for testing .

- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/types/compactor.go
This PR cherry-pick commits from the following PR:
1. #660
Fixes #
```improvement operator
Introduce flag `metrics-scrape-wait-duration` to `etcdbrctl compact` command, that specifies a wait duration at the end of a snapshot compaction, to allow Prometheus to scrape metrics related to compaction before the `etcdbrctl` process exits.
```
> Adds sleep command at the end of compaction (cherry-pick for rel-v0.24)

- doc/usage/garbage_collection.md
- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/types/snapshotter.go
Cherry-pick of https://github.com/gardener/etcd-backup-restore/pull/640
This PR resolves the request for a configurable retention period for delta snapshots. This feature aims to provide users with more flexibility in preserving delta snapshots for both GC policies (`Exponential` and `Limit-Based`) 
- Added a new `delta-snapshot-retention-period` parameter in the `SnapshotterConfig` to allow for the customization of the retention period for delta snapshots. This new setting can be adjusted via command-line flags.
- Modified the `GarbageCollectDeltaSnapshots` function, formerly `garbageCollectDeltaSnapshots`, to utilize the `DeltaSnapshotRetentionPeriod` parameter when identifying delta snapshots for deletion. This change ensures that delta snapshots …
> Implement Configurable Retention Period for Delta Snapshots #640

- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/member/member_control.go
- pkg/member/member_control_suite_test.go
- pkg/member/member_control_test.go
I found `SAP Copyrights License` was missing from some files. This PR add the missing Copyrights License to those files.
Fixes #
```improvement operator
None
```
> Add SAP Copyrights License to some file as it was missing.

- pkg/server/httpAPI.go
Currently, if someone queries `/snapshot/latest` endpoint in backup-restore server,  latest snapshots are served from whatever is stored in the already running snapshotter. But, ideally, the snapshots should be fetched from the actual backend store and then serve to the end users. This PR fetches the latest snapshots from actual store when an end user executes `/snapshot/latest` endpoint.
One use case of this PR is e2e tests for compaction. Full snapshots are stored in same storage by both the snapshotter and compactor. Currently, `/snapshot/latest` endpoint serves the latest snapshots from the details stored in snapshotter. While snapshotter has the information about what latest snapshots are pushed by itself, it does not have the information about …
> Queries the actual store to fetch latest snapshot while serving the URL endpoint.

- pkg/initializer/initializer.go
- pkg/member/member_control.go
This PR makes an `etcd-backup-restore` restart tolerant while scaling-up a etcd cluster.
This fixes the `permanent quorum loss` problem when any pod member restartes in between scaling-up of an etcd cluster.
Fixes https://github.com/gardener/etcd-druid/issues/641
```noteworthy operator
Making etcd-backup-restore restart tolerant while scaling-up an etcd cluster.
```
> Making etcd-backup-restore restart tolerant in between of scaling-up a cluster.

- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
It has been observed that sometimes during big restoration, `Embedded Etcd database space exceeds` causing the restoration failure.
This PR makes an embedded etcd lean during restoration to avoid any failure due to `etcd database space exceeds`.
To make embedded etcd lean:
- backup-restore will periodically run compaction on embedded etcd.
- backup-restore will keep a check on database size, and if it crosses certain threshold, backup-restore trigger defragmentation.
Fixes #636 
```noteworthy operator
Fix a restoration failure which can occurs due to an etcd database space exceeds during restoration.
```
> Make embedded etcd lean during restoration to avoid any restoration failure

- pkg/snapshot/restorer/restorer.go
- pkg/snapshot/restorer/restorer_test.go
Cherrypick of PR: https://github.com/gardener/etcd-backup-restore/pull/668
Fixes #
```noteworthy operator
Fix a restoration failure which can occurs due to an etcd database space exceeds during restoration.
```
> [Cherrypick #668]  Make embedded etcd lean during restoration to avoid any restoration failure

- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapstore/gcs_snapstore_test.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore_test.go
Cherrypick of PR: https://github.com/gardener/etcd-backup-restore/pull/673
Fixes #
```improvement operator
Enhanced Garbage Collector to garbage collect the chunks for cloud providers like GCP and OpenStack which does not automatically delete snapshot chunks after the formation of a composite object.
```
> [Cherrypick #673] Enhancement: Implement Chunk Deletion for Multi-part Uploaded Files on GCP and Openstack Cloud Providers

- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapstore/local_snapstore.go
This PR adds unit tests for chunk deletion by GC to make sure that GC only removes chunks and doesn't mess up with non-chunk objects in the store. And that the chunk deletion doesn't affect the general flow of operations in backup-restore.
Fixes #684
```improvement operator
Add unit tests for chunk deletion
```
> Add unit tests for chunk deletion by garbage collector

- .ci/performance_regression_test
- .ci/pipeline_definitions
- .test-defs/IntegrationTest.yaml
- Makefile
- chart/etcd-backup-restore/values.yaml
- docs/deployment/getting_started.md
GCR has been deprecated [0] in favour of Artifact-Registry.
Thus, change push-targets for OCI-Images:
- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases
- europe-docker.pkg.dev/gardener-project/public for combined view of snapshots + releases
[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.
```
> switch GCR -> Artifact-Registry

- .ci/performance_regression_test
- .ci/pipeline_definitions
- .test-defs/IntegrationTest.yaml
- Makefile
- chart/etcd-backup-restore/values.yaml
- doc/usage/getting_started.md
Cherry-pick of #688 
Fixes #
/invite @ccwienk 
/cc @ishan16696 
```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.
```
> [rel-v0.24] Switch GCR -> Artifact-Registry

- .ci/integration_test
Fix awscli installation for integration test, similar to https://github.com/gardener/test-infra/pull/480/commits/8fc1fb7f32b39aba7ddb74317cdd8dae17a8b572 (when building the testmachinery image itself).
Fixes following error from integration test:
```
Installing awscli...
error: externally-managed-environment
× This environment is externally managed
╰─> 
The system-wide python installation should be maintained using the system
package manager (apk) only.
If the package in question is not packaged already (and hence installable via
"apk add py3-somepackage"), please consider installing it inside a virtual
environment, e.g.:
python3 -m venv /path/to/venv
. /path/to/venv/bin/activate
pip install mypackage
To exit the …
```
> Fix awscli installation for integration test

- .ci/integration_test
- .ci/unit_test
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/utils.go
Dynamic loading of IaaS credentials currently involves computing the hash of the secret file and comparing the in-memory hash with the newly computed hash to check for changes in the access credentials.
When there is a change in the hash, the `SnapStore` object is updated. The computation of this hash happens whenever a delta snapshot is triggered.
This is now optimized by checking the timestamps of the credential files which were used to calculate the hash.
Currently the following providers are supported:
Fixes #449 #683 
```improvement operator
Dynamic loading of IaaS credentials is now optimized to make use of file system information instead of calculating a …
```
> Optimize dynamic loading of IaaS Credentials using credential file timestamps

- chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- docs/deployment/getting_started.md
- example/storage-provider-secrets/04-google-cloud-storage-secret.yaml
- pkg/snapstore/gcs_snapstore.go
/area backup
/platform gcp
Add support for overriding storage API endpoint for Google GCS provider. This allows users to specify their own storage API [endpoint override](https://pkg.go.dev/cloud.google.com/go#hdr-Endpoint_Override), such as a [regional endpoint](https://cloud.google.com/storage/docs/regional-endpoints), or even a local GCS emulator endpoint. Users need to set environment variable `GOOGLE_STORAGE_API_ENDPOINT`, with the value in the format `http[s]://host[:port]/storage/v1/`.
Fixes #690 
/cc @dguendisch @anveshreddy18 
/invite @ishan16696 
```improvement user
Add support for overriding storage API endpoint for provider GCS, by …
```
> Add support for overriding storage API endpoint for GCS

- .ci/integration_test
- chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- doc/usage/getting_started.md
- example/storage-provider-secrets/04-google-cloud-storage-secret.yaml
- pkg/snapstore/gcs_snapstore.go
/area backup
/platform gcp
Cherry-pick of #691 
Fixes #
/invite @ishan16696 @anveshreddy18 
```improvement user
Add support for overriding storage API endpoint for provider GCS, by setting environment variable `GOOGLE_STORAGE_API_ENDPOINT`, with the value in the format `http[s]://host[:port]/storage/v1/`. ⚠️ Note: GCS storage API endpoint will not be overridden for `copy` subcommand, since backup buckets may reside in different regions.
```
> [rel-v0.24] Add support for overriding storage API endpoint for GCS

- .ci/integration_test
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/utils.go
Cherry-pick of #670
Fixes #
```improvement operator
Dynamic loading of IaaS credentials is now optimized to make use of file system information instead of calculating a hash of the credentials to detect changes.
```
> [rel-v0.24] Optimize dynamic loading of IaaS Credentials using credential file timestamps

- Makefile
Fix artifact registry issue to push images used for development purposes to `europe-docker.pkg.dev/gardener-project/snapshots`
Fixes #
```improvement operator
NONE
```
> Fix artifact registry issue  

- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/swift_snapstore_test.go
This PR fixes a recent regression in chunk deletion behavior for Openstack Swift snapshots. Additionally, remove backward compatibility tests between `v1` and `v2` for garbage collection, since `v1` is no longer supported. Support for `v1` backup directory structure in other parts of the code should be gradually removed as well, but not in this PR, to avoid scope spill.
Fixes #702
/cc @plkokanov 
/invite @ishan16696 @anveshreddy18 @seshachalam-yv 
```improvement operator
A regression in chunk deletion behavior for openstack provider has now been fixed.
```
> Fix regression in chunk deletion for openstack provider

- .ci/pipeline_definitions
/area delivery
This PR adds the `gardener/etcd-druid-maintainers` team as responsibilities to the component descriptor, similar to https://github.com/gardener/etcd-druid/pull/758.
```improvement operator
NONE
```
> Add etcd team to component descriptor

- chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- example/storage-provider-secrets/00-azure-blob-storage-secret.yaml
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/snapstore.go
- pkg/snapstore/snapstore_test.go
Changes to make `etcd-backup-restore` work with [`Azurite`](https://github.com/Azure/Azurite#introduction) - the Azure Blob Storage emulator to enable easier local development and testing.
Two new environment variables are introduced to make use of `Azurite` with `etcd-backup-restore`:
- `EMULATOR_ENABLED` - indicates whether `Azurite` is being used instead of ABS infrastructure. Takes boolean values, and hence can be set to `true` or `false`.
- `AZURE_STORAGE_API_ENDPOINT` - stores the endpoint at which `Azurite` is hosted. For example, if `Azurite` is hosted at `http://localhost:10000`, `AZURE_STORAGE_API_ENDPOINT` is set to this address. `etcd-backup-restore` reacts to the presence of this environment variable and sets the endpoint for `Azurite` …
> Enhancing `etcd-backup-restore` to support `Azurite` - the Azure Blob Storage emulator

- .reuse/dep5
AFAIR, some part of code in restorer file was copied from upstream etcd. Hence updating the `.reuse/dep5` file
Addressing this comment:  https://github.com/gardener/etcd-backup-restore/pull/714#issuecomment-1963340490
@shreyas-s-rao 
```improvement operator
None
```
> Updated the .reuse/dep5 file.

- pkg/health/heartbeat/heartbeat.go
The recently merged PR #711 had introduced a small change in wrongly deciding that If there's no revision change for full snapshot lease, then don't renew it. But the opposite was originally introduced in PR #410 as a deliberate change so that even if there are no events in the last 24h ( which leads to the current full snapshot having the same revision as previous ) we still want to renew the full snapshot lease because it helps in not marking the full snapshot health check as failed although it was not actually a failure but a case of `skipping the full snapshot` ( May happen in idle dev shoot clusters in landscapes )
Fixes #
```improvement developer
NONE
```
> Fix a full snapshot lease renewal decision

- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
Fix statefulset to treat provider config env vars as optional. This allows users to not define certain non-mandatory fields in the provider secrets, which the statefulset can then ignore, instead of forcing the fields to be present in the provider secrets. 
Fixes #
/cc @renormalize @anveshreddy18 
```improvement operator
NONE
```
> Fix statefulset to treat provider config env vars as optional

- pkg/server/backuprestoreserver.go
As reported in #676 we sometimes see that multiple snapshotters can be running at one time in a cluster. 
I believe that the reason for this is that the snapshotter is not set to active state until an initial delta snapshot or a fullsnapshot has been taken. If a leadership election takes place while the snapshot is being taken and the current leader loses that election, then handleSsrRequest does not send on the ssrStopCh. This in turn causes ssr.snapshotEventHandler to never return and snapshots would continue to be taken.
Secondly I'm propsing a change to close the `ssrStopCh` rather than sending on it. This is to make it clear to the reader that the channel is no longer being used at this point. 
Lastly the function signature changes are simply …
> Do not check SSR State when Snapshotter should be stopped

- chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- example/storage-provider-secrets/04-google-cloud-storage-secret.yaml
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/snapshot.go
- pkg/snapstore/snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/types/snapstore.go
* Add a new field `emulatorEnabled` in gcp secret
* configure Google cloud client for GCS Emulator when `emulatorEnabled` is `true`
This is helpful to run `etcdbr` tests locally and on pipelines without actually using the real infra. This can also be used by [Etcd-druid](https://github.com/gardener/etcd-druid) to use GCS Emulator [fake-gcs-server](https://github.com/fsouza/fake-gcs-server) for running e2e-tests.
For these, Google cloud client in `backup-restore` has to be configured to connect to the Emulator. 
This PR enables that in either of the two ways 
1) `GOOGLE_EMULATOR_ENABLED` env var is set when running `etcdbr` as a process using `etcdbrctl` 
2) `emulatorEnabled` field in the gcp secret is set to `true` via helm chart
**Which issue(s) …
> [FakeGCS] Add a new field `emulatorEnabled` in gcp secret & configure Gcloud client for GCS Emulator

- docs/development/local_setup.md
Running `etcdbrctl` locally as a process is quite useful for testing, since it enables faster iteration and smaller build times.
Lack of this documentation was a problem for the contributor in #719, and the diff here was added as a comment in it. The comment is repurposed and formatted to fit the docs here.
The rest of `docs/development/local_setup.md` was updated in relevant places, like minimum Go version, output of `etcdbrctl -v`.
Fixes #
```improvement developer
Added documentation to use `etcdbrctl` as a process for testing locally, for a better developer experience and faster iteration speeds.
```
> Add documentation to run `etcdbrctl` as a process locally

- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- docs/deployment/getting_started.md
- pkg/snapstore/generic_s3_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/snapstore_test.go
This PR enables setting up Server-Side Encryption using SSE-C(Not AWS managed keys) keys for S3-compatible providers
Fixes #718
None
```improvement operator
etcd-backup-restore now supports server-side encryption using customer provided keys (SSE-C) for S3-compatible providers
```
> Setup SSE with customer provided keys (SSE-C) for S3-compatible providers

- pkg/snapstore/s3_snapstore.go
This is mostly a typo bug from the previous sse [PR](https://github.com/gardener/etcd-backup-restore/pull/719)
> Set appropriate SSE Customer Key and MD5 in `S3SnapStore.uploadPart()` for SSE-C

- docs/deployment/getting_started.md
- example/storage-provider-secrets/00-azure-blob-storage-secret.yaml
- example/storage-provider-secrets/01-aws-s3-storage-secret.yaml
- example/storage-provider-secrets/02-openstack-swift-storage-secret.yaml
- example/storage-provider-secrets/03-ali-cloud-object-storage-secret.yaml
- example/storage-provider-secrets/05-openshift-container-storage-secret.yaml
- pkg/server/backuprestoreserver.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/ocs_s3_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/swift_snapstore.go
- pkg/snapstore/utils.go
The dual way of passing credentials to etcd-backup-restore, but the file-type agnostic way of passing credentials in [gardener/etcd-druid](https://github.com/gardener/etcd-druid) caused confusion in the community consuming both etcd-druid and etcd-backup-restore.
Passing credentials through a JSON file in etcd-druid does not cause it to error, but is not supported by etcd-druid - and thereby causes etcd-backup-restore to error as a result, even though etcd-backup-restore supports credentials in JSON files. 
If consumers familiar with etcd-backup-restore who pass credentials as JSON typically, use the same method to pass credentials in etcd-druid, etcd-backup-restore errors.
To temporarily solve this, if credentials are passed through a JSON file in …
> Add support to read JSON credential files present in a directory passed through the `<PROVIDER>_APPLICATION_CREDENTIALS` environment variable

- .ci/integration_test
/kind task
Switch from `/cc/utils/cli.py` to `gardener-ci` command available in `$PATH`, for integration tests.
Fixes #
```improvement operator
NONE
```
> Switch to `gardener-ci` for integration tests

- pkg/snapshot/snapshotter/fullsnapshotleaseupdate.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/types/health.go
This PR removes the flag `full-snapshot-lease-update-interval` from the etcdbr API. The flag was introduced in PR #711 to let druid configure the interval for retrying to update full snapshot lease when the lease is stale. But from the internal discussions among the team, we've decided that this flag is of not much help and unnecessarily extends the API. So this PR removes the flag. 
Also update the default retry interval from `3 min` to `1 min` to allow faster periodic retry. For more information refer PR #711.
Fixes #
```improvement operator
Reverted the decision to have the flag `full-snapshot-lease-update-interval` to configure periodic interval for full …
```
> Remove the `full-snapshot-lease-update-interval` flag from etcdbr API

- pkg/compactor/compactor.go
- pkg/health/heartbeat/heartbeat.go
- pkg/health/heartbeat/heartbeat_test.go
- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/fullsnapshotleaseupdate.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/types/health.go
cherry-pick of PR #711, #720, and #744 combined together
Fixes #
```improvement operator
Introduce periodic updates to the Full Snapshot Lease, addressing delays in lease updates during failures
```
> [rel-v0.28] Full snapshot lease update retry on failure

- .ci/build
- .ci/check
- .ci/integration_test
- Makefile
- docs/development/new_cp_support.md
- go.mod
* `make check` failed to run correctly locally - fixed by using `go install`.
* Remove references to the deprecated `GO111MODULE`.
* Fixed a broken link in `docs/development/new_cp_support.md`.
```improvement developer
Fixed the `check` make target when run locally, and a link in docs/development/new_cp_support.md.
```
> Fix `make check` and other house keeping

- docs/deployment/getting_started.md
- example/storage-provider-secrets/00-azure-blob-storage-secret.yaml
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/abs_snapstore_test.go
- pkg/types/snapstore.go
* Add support to override the domain for ABS in `pkg/snapstore/abs_snapstore.go`.
* Adapt example in `example/storage-provider-secrets/00-azure-blob-storage-secret.yaml` to explain the override feature.
* Enhance documentation to explain the override feature in `docs/deployment/getting_started.md`.
For example if a consumer provides the overriding `domain` as `blob.core.windows.net`, the service URL that is formed will be:
```
https://<storage-account>.blob.core.windows.net
```
Similarly, if the overriding `domain` is provided as `blob.core.chinacloudapi.cn`, then the service URL that is formed will be:
```
https://<storage-account>.blob.core.chinacloudapi.cn
```
Fixes #757
cc …
> Add support to override Azure Blob Storage Domain

- chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- chart/etcd-backup-restore/values.yaml
- docs/deployment/getting_started.md
- example/storage-provider-secrets/00-azure-blob-storage-secret.yaml
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/abs_snapstore_test.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/types/snapstore.go
As mentioned in #727, it is not secure to be passing credential (secret) information to the etcdbr process via environment variables. This is ok while running locally, but when running on a k8s cluster (deployed by etcd-druid), it becomes important for etcdbrctl to be able to fetch the information about endpoint overrides directly from the mounted secret file, where the other default credentials already exist today.
This PR does two things:
1. For provider GCP, adds support for specifying `storageAPIEndpoint` via file path, while still supporting the environment variable `GOOGLE_STORAGE_API_ENDPOINT` env var (for users who may already be using it.
2. For provider Azure, removes support for `AZURE_STORAGE_API_ENDPOINT` and now uses field `domain`, …
> Stop using `*_STORAGE_API_ENDPOINT` environment variables

- pkg/initializer/initializer.go
This PR will fix a bug in detection of a single member restoration case when snapstore is not configured for zeroth pod.
Fixes #760 
```bugfix operator
Fixed a bug in detecting single member restoration scenario for the zeroth pod and when no storage provider for backups is configured.
```
> Fix a detection for a single member restoration when snapstore is not configured for zeroth pod.

- pkg/server/backuprestoreserver.go
- pkg/snapshot/snapshotter/snapshotter.go
- pkg/snapshot/snapshotter/snapshotter_test.go
Cherry-pick PR : https://github.com/gardener/etcd-backup-restore/pull/765
Fixes #
```improvement operator
Retry to take full snapshot if the previous full snapshot operation fails.
```
> [Cherry-pick #765] Retry to take full snapshot if prev full snapshot fails due to any reason.

- pkg/initializer/initializer.go
Cherry-pick PR:  https://github.com/gardener/etcd-backup-restore/pull/761
Fixes #
```bugfix operator
Fixed a bug in detecting single member restoration scenario for the zeroth pod and when no storage provider for backups is configured.
```
> [Cherry pick #761] Fix a detection for a single member restoration when snapstore is not configured for zeroth pod.

- pkg/initializer/initializer.go
I forgot to remove this err handling in this PR: https://github.com/gardener/etcd-backup-restore/pull/761
Fixes #
```improvement operator
None
```
> Removed useless error handling.

- Makefile
* The `docker-build` make target builds the image for the architecture of the host machine (same behavior as before).
* The platform can be overridden by passing this variable directly to the make command like `PLATFORM=linux/arm64 make docker-build`, `PLATFORM=linux/amd64 make docker-build`.
```improvement developer
Builds for non-native platforms can now be done using the `docker-build` make target instead of having to invoke the `docker buildx` command. The platform can be specified using the `PLATFORM` variable which is passed while invoking make.
```
> Enhance the `docker-build` make target to build for multiple platforms.

- docs/usage/immutable_snapshots.md
- pkg/compactor/compactor_test.go
- pkg/miscellaneous/miscellaneous.go
- pkg/miscellaneous/miscellaneous_test.go
- pkg/snapshot/copier/copier.go
- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter_test.go
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/failed_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/gcs_snapstore_test.go
- pkg/snapstore/local_snapstore.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/snapshot_test.go
- pkg/snapstore/snapstore_test.go
- pkg/snapstore/swift_snapstore.go
- pkg/types/snapstore.go
- test/e2e/integration/cloud_backup_test.go
- test/e2e/integrationcluster/backup_test.go
- test/e2e/integrationcluster/utils.go
Enables etcd-backup-restore to handle immutable objects as provided by [bucket lock](https://cloud.google.com/storage/docs/bucket-lock) in Google Cloud Storage.
* A new method `IsDeletable()` is added to the `Snapshot` `struct`. This method returns a `bool` which informs the caller whether the `Snapshot` instance can be deleted from the object store. It internally checks the immutability expiration time of the object and returns `true` if it has expired.
* [Custom metadata](https://cloud.google.com/storage/docs/metadata#custom-metadata) can be added to objects in Google Cloud Storage. In case any particular object (snapshot) is to be excluded during restoration, custom metadata can be added to that object with the key `x-etcd-snapshot-exclude` and …
> Add `Bucket Lock` immutable object support for Google Cloud Storage.

- .ci/pipeline_definitions
Use the standard Go distribution image for integration tests in the pipeline instead of the testmachinery image.
This will improve build reproducibility for older branches, since it specifies a version instead of a `latest` or `stable` tag.
```improvement developer
NONE
```
> Use the standard Go distribution image for integration tests in the pipeline instead of the testmachinery image.

- .ci/integration_test
* Install AWS CLI v2 through `curl` instead of the older version through `pip`.
* Pull in `gardener-cicd-cli` through `pip`.
cc @seshachalam-yv 
```improvement developer
NONE
```
> Install the AWS CLI v2 through `curl`, instead of `pip`.

- example/00-backup-restore-server-config.yaml
- pkg/member/member_control.go
- pkg/miscellaneous/miscellaneous.go
- pkg/server/backuprestoreserver.go
- pkg/server/init.go
- pkg/server/types.go
- pkg/types/etcdconnection.go
- test/e2e/integration/cloud_backup_test.go
1. Backup-restore will now call [updateMemberPeerURL](https://github.com/etcd-io/etcd/blob/fe7d1904d256f9eef66244b67069e6e87e08a816/clientv3/cluster.go#L49) API call only when peerURL is found to be updated.
2. Backup-restpre will now restart it's corresponding etcd member after updating etcd's advertise peer URLs  if found to be updated.
3. Introduced a CLI flag `--use-etcd-wrapper`(default: false)  to enable/disable backup-restore to use etcd-wrapper related functionality.
Fixes #787 
This PR needs to be tested  with PR of etcd-wrapper: https://github.com/gardener/etcd-wrapper/pull/31 where `/stop` endpoint is introduced with `--use-etcd-wrapper` set to `true` for …
> Backup-restore now restart the etcd member incase of etcd's advertise peerURL found to be updated.

- example/00-backup-restore-server-config.yaml
- pkg/member/member_control.go
- pkg/miscellaneous/miscellaneous.go
- pkg/server/backuprestoreserver.go
- pkg/server/init.go
- pkg/server/types.go
- pkg/types/etcdconnection.go
- test/e2e/integration/cloud_backup_test.go
Cherry-pick PR of https://github.com/gardener/etcd-backup-restore/pull/788
Fixes #
```noteworthy operator
etcd-backup-restore now triggers a restart of the etcd member after updating etcd's advertise peer URLs if found updated.
```
```noteworthy user
Introduced a CLI flag `--use-etcd-wrapper` (default: false) to enable/disable the backup-restore to use etcd-wrapper related functionality. Note: enable this flag only if etcd-wrapper is deployed.
```
> [rel-v0.30] Backup-restore now restart the etcd member incase of etcd's advertise peerURL found to be updated.

- pkg/snapshot/snapshotter/garbagecollector.go
- pkg/snapshot/snapshotter/snapshotter_test.go
This PR changes the error handling for deletion of delta snapshots by replacing the current implementation with concatenation of errors using the errors.Join() method upto a threshold of 5. The process of continues with the deletion of the rest of the "deletable" delta snapshots even when an error is encountered, instead of halting the process. When the number of errors becomes greater than the threshold, it errors out for the current cycle.
Fixes #652 
```other operator
Improved error handling in deletion of delta snapshots during snapshot garbage collection.
```
> Improved error handling in deletion of delta snapshots during snapshot garbage collection

- go.mod
Adhere to https://github.com/gardener/gardener/pull/9564
Fixes #
@gardener/etcd-druid-maintainers 
```noteworthy developer
`etcd-backup-restore` will henceforth stick to Go versions `x.y.0` only to be in line with gardener/gardener, kubernetes, controller-runtime.
```
> Use `x.y.0` versions of the Go Toolchain only

- go.mod
Cherry-pick of #801
Fixes #
```noteworthy developer
`etcd-backup-restore` will henceforth stick to Go versions `x.y.0` only to be in line with gardener/gardener, kubernetes, controller-runtime.
```
> [rel-v0.31] Use `x.y.0` versions of the Go Toolchain only (#801)

- .ci/check
- pkg/mock/etcd/clientv3/mocks.go
- pkg/mock/etcdutil/client/mocks.go
Enhance the `check` make target to ensure the Go version adheres to `x.y.0`.
Fixes #
The diff in the `mocks.go` file is just an import order rearrange that automatically happened after running `make check`.
```improvement developer
Enhanced the `check` make target to ensure the Go version adheres to `x.y.0`.
```
> Enhance the `check` make target to ensure the Go version adheres to `x.y.0`.

- pkg/snapshot/snapshotter/snapshotter.go
This PR ensures that the backup-restore process does not skip a scheduled full snapshot, even when no events occur during the interval between two full snapshot schedules.
Fixes #797 
The current implementation allows for taking a full snapshot in all cases, except the case where the preceding full snapshot has been set as final.
```improvement operator
Don't skip full snapshot, always trigger a full snapshot independent of new updates to etcd, preventing prometheus alerts of not taking a scheduled full snapshot.
```
> Prevent skipping scheduled full snapshots when there are no new updates

- docs/usage/immutable_snapshots.md
Improve `docs/usage/immutable_snapshots.md`, adding example commands to make buckets immutable.
This improvement is useful for https://github.com/gardener/etcd-druid/pull/884.
```improvement developer
Example commands to make buckets immutable added to the documentation for the currently supported providers.
```
> Improve `docs/usage/immutable_snapshots.md`, adding example commands to make buckets immutable.

- chart/etcd-backup-restore/templates/etcd-statefulset.yaml
- pkg/snapstore/abs_snapstore.go
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/snapstore.go
- pkg/snapstore/snapstore_test.go
- pkg/types/snapstore.go
/area compliance security
/kind task
Read `emulatorEnabled` value for storage emulators from mounted secret instead of environment variables, to avoid mounting and exposing data from secrets as environment variables, even if they are non-credential fields.
Changes in this PR:
Fixes #
/invite @anveshreddy18 @renormalize 
```improvement user
Remove usage of environment variables to determine whether storage emulators are enabled.
```
> Read `emulatorEnabled` value for storage emulators from mounted secret instead of environment variables

- .ci/pipeline_definitions
/area usability
Tag docker images built via pipeline release process as `latest`, to allow users to use the latest version of etcdbrctl as `europe-docker.pkg.dev/gardener-project/public/gardener/etcdbrctl:latest`, without needing to specify the latest released version of the component.
Fixes #
/invite @renormalize @anveshreddy18 
```improvement user
Tag docker images built via pipeline release process as `latest`.
```
> Tag docker images built via pipeline release process as `latest`

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/support.md
/area open-source
/kind task
Replace occurrences of `etcd-druid` with `etcd-backup-restore` in the github issue templates.
Fixes #
```other operator
NONE
```
> Fix github issue templates

- cmd/compact.go
- cmd/copy.go
- cmd/initializer.go
- cmd/options.go
- cmd/restore.go
- cmd/snapshot.go
/area logging
/kind bug
* Set `controller-runtime` logger to `log.NullLogSink{}` to avoid `[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.` logs from being printed.
This PR takes inspiration from https://github.com/rook/rook/pull/12448 for `log.NullLogSink{}`.
Fixes #827 
```bugfix developer
NONE
```
> Set `controller-runtime` logger to `log.NullLogSink{}`

- chart/etcd-backup-restore/values.yaml
/kind task
Switch `etcd-backup-restore` image & version to `europe-docker.pkg.dev/gardener-project/public/gardener/etcdbrctl` & `latest` respectively in values.yaml of the helm charts
Fixes #829 
```other user
use etcdbr `latest` tagged image in the helm charts
```
> Update etcdbr image tag to latest in helm charts

- .ci/pipeline_definitions
- build/Dockerfile
/area security compliance quality
/kind task
Update golang version to `1.23.5` which brings [security fixes](https://go.dev/doc/devel/release#go1.23.5).
```other dependency
Update golang version to `1.23.5`.
```
> Update golang version to 1.23.5

- pkg/defragmentor/defrag_test.go
- pkg/defragmentor/defragmentor_suite_test.go
- pkg/etcdutil/etcdutil_suite_test.go
- pkg/etcdutil/etcdutil_test.go
/area backup
/area testing
/kind test
We noticed that some of the unit tests present in `pkg/defragmentor_test` should be present in `pkg/etcdutil_test`, hence we decided to move the some of the unit tests from `pkg/defragmentor_test` -> `pkg/etcdutiil_test`.
More info: https://github.com/gardener/etcd-backup-restore/issues/800#issuecomment-2626785569
Fixes #800 
```other operator
None
```
> Moved some of the unit tests from `pkg/defragmentor_test` to `pkg/etcdutiil_test`

- docs/usage/enabling_immutable_snapshots.md
- pkg/snapstore/s3_snapstore.go
/area documentation
This PR improves the documentation for [enabling immutable objects](https://github.com/gardener/etcd-backup-restore/blob/master/docs/usage/enabling_immutable_snapshots.md). I have restructured the document into separate sections for each storage provider, making it easier for users to find and follow the relevant instructions, making it easier to navigate for them, especially for users seeking information about specific providers. 
This will also improves the maintainability as it will become easy to add more provider information in future.
Fixes #839 
I have also added 1 more commit to add few logs.
**Release …
> Refactor the enabling of immutable snapshots doc

- docs/usage/enabling_immutable_snapshots.md
- pkg/snapstore/gcs_snapstore.go
- pkg/snapstore/s3_snapstore.go
- pkg/snapstore/s3_snapstore_test.go
- pkg/snapstore/snapstore_test.go
- pkg/types/snapstore.go
/area security
/kind technical-debt
This PR adds a support of skipping/ignoring of any snapshot in an object lock enabled S3 bucket using tag method.
It is achieved in a two-step:
1. Put a delete marker on the top of object. Please refer [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html) for more information regarding deletion in versioning enabled S3 bucket.
2. Then add a tag to snapshot object which you wish to be skipped/ignored during restoration:
- **Key:** `x-etcd-snapshot-exclude`
- **Value:** `true`
Fixes #843 
```noteworthy user
Added a support for skipping or ignoring any snapshot in …
```
> Added a support of skipping/ignoring of any snapshot in an object lock enabled S3 bucket.

- Makefile
/area dev-productivity
/kind task
Fixes the release notes in `rel-v0.35`.
Fixes the release notes in `rel-v0.35`.
This PR adds release notes of commits that were directly added to `rel-v0.35`, and not added as PRs.
The branch was created by editing the bump commit instead of cherry-picking all commits from master to `rel-v0.35` through PRs. This should be avoided in the future.
```noteworthy user
Added a support for skipping or ignoring any snapshot in an object lock-enabled S3 bucket. For more information please refer to this doc: https://github.com/gardener/etcd-backup-restore/blob/master/docs/usage/enabling_immutable_snapshots.md …
```
> Nit: reorder args in Makefile.

- hack/config/gcp_config.sh
- hack/e2e-test/run-e2e-test.sh
- test/e2e/backup_test.go
- test/e2e/utils.go
/area testing
/kind test
The PR #743 restored the e2e tests and made them run with cloud providers(real infra & their emulators), to make that happen it installs the provider CLIs such as `awscli`, `az` and `gcloud` to interact with both real providers and emulators. The current code uses `pip3` to install these CLI tools but we plan to run these tests in prow environment where they run inside a Debian linux container where pip3 is not present by default. So the PR makes changes to install these tools using `apt` pkg manager which is native to Debian environments. 
This PR also fixes a failing e2e test case where the `pgrep` command to get the PID of the `etcd-wrapper` process is not working as intended, changed it to …
> Changes in e2e tests setup required for running them in prow job environment

- hack/config/gcp_config.sh
- hack/e2e-test/run-e2e-test.sh
- pkg/server/httpAPI.go
- test/e2e/backup_test.go
- test/e2e/utils.go
CherryPick of PR: https://github.com/gardener/etcd-backup-restore/pull/764
Fixes #
```improvement operator
Support non-HA autonomous clusters by skipping creation of Kubernetes clientset.
⚠️ To completely prevent the creation of the Kubernetes `clientSet` in the non-HA etcd-backup-restore, please also set the following CLI flags to `false`: `--enable-member-lease-renewal` and `--enable-snapshot-lease-renewal`.
```
> Support non-HA autonomous clusters (#764)

- pkg/initializer/initializer.go
- pkg/member/member_control.go
- pkg/server/httpAPI.go
- pkg/snapstore/utils.go
- pkg/types/snapstore.go
/area security compliance
/kind task cleanup
Clean up snapshot temp directory during initialization, to ensure any previously created temp files for snapshot upload will be cleaned up, which helps in two ways (a) to remove unnecessary files which may not have been properly cleaned up in a previous run of etcdbr and (b) these older files might have old file permissions before umask of 0077 was set, which might violate [DISA STIG](https://www.stigviewer.com/stig/kubernetes/) standards, hence cleaning up these files is beneficial from a security perspective as well.
Fixes #
```other user
Clean up snapshot temp directory during …
```
> Clean up snapshot temp directory during initialization

- hack/test-unit.sh
- pkg/snapstore/utils.go
- pkg/snapstore/utils_test.go
/area backup
/kind regression bug
Fix regression caused by #869, due to which snapshot temp directory was not getting created, specifically for compaction command that doesn't use `initializer` package to initialize the directories. The code which was erroneously removed was [this](https://github.com/gardener/etcd-backup-restore/pull/869/files#diff-29fda098b6a688bb2dc41eb985a767e795ffcbe1c3cd788b12148cab0ea4f21fL49-L61), in an attempt to clean up redundant code. This PR adds that code back.
Fixes #
/invite @seshachalam-yv @anveshreddy18 
```bugfix user
Fix regression in cleanup of snapshot temporary directory.
```
> Fix regression in cleaning up snapshot temp directory during initialization

- hack/test-unit.sh
- pkg/snapstore/utils.go
- pkg/snapstore/utils_test.go
/area backup
/kind regression bug
Cherry-pick of #875 
Fixes #
```bugfix user
Fix regression in cleanup of snapshot temporary directory.
```
> [rel-v0.36]  Fix regression in cleaning up snapshot temp directory during initialization

- pkg/initializer/initializer.go
/area backup
/kind regression bug
Fix regression for snapshot temp dir cleanup when no snapstore configured, by checking for whether snapstoreConfig is configured before attempting to clean up the temporary directory.
Fixes #880 
/invite @anveshreddy18 @seshachalam-yv 
```bugfix user
Fix regression for snapshot temp dir cleanup when no snapstore configured.
```
> Fix regression for snapshot temp dir cleanup when no snapstore configured

- docs/usage/enabling_immutable_snapshots.md
- pkg/snapstore/internal/ossApi/interface.go
- pkg/snapstore/oss/interface.go
- pkg/snapstore/oss_snapstore.go
- pkg/snapstore/oss_snapstore_test.go
- pkg/snapstore/snapstore_test.go
/area compliance
/area security
This PR introduces support for `WORM immutable objects` in Alibaba Cloud's Object Storage Service (OSS) by modifying the garbage collection functionality to manage immutable snapshots. Additionally, it updates the documentation in `docs/usage/immutable_snapshots.md`.
Fixes #879 
```noteworthy operator
etcd-backup-restore now supports worm immutable objects for storage provider: ALI Cloud OSS, provided by the [WORM Lock](https://www.alibabacloud.com/help/en/oss/developer-reference/worm) feature.
```
```noteworthy operator
Snapshots garbage collection performed by etcd-backup-restore …
```
> Add support for `WORM immutable objects` for ALI cloud's  OSS.
