gardener/etcd-backup-restore

cmd/root.go, cmd/server/server.go, example/etcd-statefulset.yaml, pkg/errors/error.go, pkg/initializer/initializer.go, pkg/initializer/validator/datavalidator.go, pkg/server/httpAPI.go, pkg/snapshot/snapshotter/snapshotter.go, pkg/snapshot/snapshotter/types.go
* Fixes the data directory validation related issues in last commit.
* Adds HTTP server to expose functionality over http.
=> Expose etcd initialiation functionaliy over http

.gitignore, cmd/initializer/initializer.go, cmd/initializer/restore.go, cmd/server/server.go, cmd/snapshot/snapshot.go, example/etcd-statefulset.yaml, pkg/initializer/initializer.go, pkg/initializer/types.go, pkg/snapstore/utils.go
=> Add store prefix option

cmd/initializer.go, cmd/miscellaneous.go, cmd/restore.go, cmd/root.go, cmd/server.go, cmd/snapshot.go, cmd/types.go, pkg/initializer/initializer.go, pkg/initializer/types.go, pkg/snapstore/types.go, pkg/snapstore/utils.go
=> Refactore code and allow no backup options

.ci/build, .ci/check, .ci/test, .gitignore, Makefile
=> Fix the CI scripts

cmd/restore.go, pkg/initializer/initializer.go, pkg/snapshot/restorer/restorer.go, pkg/snapshot/snapshotter/snapshotter.go, pkg/snapstore/abs_snapstore.go, pkg/snapstore/gcs_snapstore.go, pkg/snapstore/local_snapstore.go, pkg/snapstore/s3_snapstore.go, pkg/snapstore/s3_snapstore_test.go, pkg/snapstore/snapshot.go, pkg/snapstore/snapshot_test.go, pkg/snapstore/snapstore_test.go, pkg/snapstore/swift_snapstore.go, pkg/snapstore/types.go
=> Update backup directory structure

.ci/integration_test, .ci/pipeline_definitions, .ci/test, CHANGELOG.md, README.md, pkg/snapstore/snapshot_test.go
=> Add integration test setup

pkg/snapshot/restorer/restorer.go, pkg/snapshot/snapshotter/snapshotter.go
=> Add hash verification to delta snapshots

.ci/integration_test, .gitignore, README.md, test/e2e/integration/cloud_backup_test.go
=> Fix integration test ID generation

pkg/initializer/initializer.go, pkg/snapshot/snapshotter/garbagecollector.go, pkg/snapstore/gcs_snapstore.go, test/e2e/integration/cloud_backup_test.go
=> Fix integration test for limit based garbage collection

README.md
This pull request adds documentation for flags pertaining to incremental snapshot and garbage collection.
=> Adding documentation for incremental snapshot and garbage collection.

.ci/pipeline_definitions
=> use different golang image for tests

.ci/integration_test, test/e2e/integration/cloud_backup_test.go
Fixes #
Integration test that validates that etcd backup-restore does not run into a deadlock in case of etcd failure due to etcd crash or data corruption.
```improvement operator
```
=> Integration test to check deadlock.

CODEOWNERS
Since Shreyas is working full time on development and maintenance of this repo, this PR adds him to maintainers list.
Fixes #
```improvement operator
NONE
```
=> Add Shreyas Rao to maintainers.

pkg/snapshot/snapshotter/snapshotter.go
This fixes a memory/goroutine leak that caused several gouroutines and memory to leak every time a full snapshot was execucted because the old watch was never closed and continued to receive updates that were not processed.
From the etcd client godocs:
> The context "ctx" MUST be canceled, as soon as watcher is no longer being used, to release the associated resources.
https://github.com/etcd-io/etcd/blob/4cd0bf8ea846a0d158761d55899f631eb2a423cf/clientv3/watch.go#L52-L53
It fixes a serious memory leak
Not sure maybe #102
From Converged Cloud Enterprise Edition with ❤️ 
```noteworthy operator
Fixed memory/goroutine leak: close previous Etcd watches
```
=> Fix memory leak during full snapshot

CHANGELOG.md, chart/values.yaml, example/etcd-statefulset-aws.yaml, example/etcd-statefulset-azure.yaml, example/etcd-statefulset-gcp.yaml, example/etcd-statefulset-local.yaml, example/etcd-statefulset-openstack.yaml, hack/templates/etcd-statefulset.yaml.tpl
This PR updates image tags in documentation, helm chart and examples to 0.5.0. 
Should we get rid of the `example` directory, because we now have helm chart itself. If not, would it be required to add the Alibaba OSS YAML as well to the `example` directory?
```improvement operator
NONE
```
=> Update image tags to 0.5.0

pkg/snapshot/snapshotter/garbagecollector.go, pkg/snapshot/snapshotter/snapshotter.go, pkg/snapstore/gcs_snapstore_test.go
Just small refactoring in garbageCollector.go, to make code little more readable.
Fixes #
```improvement operator
NONE
```
=> Refactor garbage collector

build/Dockerfile
Fixes #
```improvement operator
Updated the base image of alpine in docker container to 3.9.3. 
```
=> Update the docker alpine base image.

pkg/etcdutil/defrag_test.go
This tries to fix the intermittent failure of defragmentation unit test.
Fixes #
```improvement operator
NONE
```
=> Fix defragmentation unit tests

pkg/snapshot/restorer/restorer.go, pkg/snapstore/snapshot.go, pkg/snapstore/snapshot_test.go
Fixes #
```improvement user
Fixed the sorting of snapshots. 
```
=> Consider prefix while the sorting for snapshots

.ci/check
This PR adds the task of helm chart linting to the check step of the CI pipeline.
Fixes #
```improvement operator
NONE
```
=> Add helm chart linting check in CI pipeline

pkg/metrics/metrics.go
This PR fixes the inconsistent behavior of the metrics helper functions by employing fixed-length slices for deterministic behavior in order for the `reflect.DeepEqual` comparison to return true during tests.
Fixes #
```improvement operator
NONE
```
=> Fix metrics helper functions for consistent behavior of slice capacity

cmd/server.go, pkg/server/httpAPI.go, pkg/server/httpAPI_test.go
Log the health status change so that we debug issues with etcd readiness.
```improvement operator
The health status changes are now logged at `INFO` level to help debug issues with etcd readiness.
```
=> Log health status change.

pkg/snapstore/oss_snapstore.go
Fixes #
```improvement operator
Fix the object listing for OSS snapstore
```
=> Fix oss object listing

README.md, doc/proposals/restoration.md, doc/usage/manual_restoration.md
This PR adds a separate document that guides operators on how to perform a manual restoration of etcd data.
Fixes #
```improvement operator
NONE
```
=> Add document for manual restoration steps

pkg/initializer/initializer.go
This PR fixes the bug where for a fresh etcd dir, restoration metric would be observed initially even though a restoration didn't actually happen. Because of this, the metric `etcdbr_restoration_duration_seconds_count` would be set to 1 instead of 0 when `etcdbrctl` process starts on a fresh data directory.
Fixes #
```improvement operator
NONE
```
=> Fix restoration metric

doc/usage/manual_restoration.md
This PR adds documentation about how to force a manual restoration in case the automatic restore isn't triggered.
Fixes #216 
```improvement operator
Add documentation to force restore etcd data.
```
=> Add documentation for forced manual restore

.ci/pipeline_definitions
This PR fixes issue in integration test by updating the job image.
Fixes #
```improvement operator
NONE
```
=> Update integration test job image

.ci/performance_regression_test, README.md, doc/development/testing_and_dependencies.md, doc/development/tests.md
This PR adds documentation for integration tests.
Fixes #
```improvement operator
NONE
```
=> Add test documentation

chart/etcd-backup-restore/templates/etcd-statefulset.yaml, chart/etcd-backup-restore/values.yaml
Changed the chart to store local backup in the PV. Also, updated the image version.
Fixes #
```improvement operator
NONE
```
=> Changed the chart to store local backup in the PV.

chart/etcd-backup-restore/templates/etcd-backup-secret.yaml, chart/etcd-backup-restore/templates/etcd-statefulset.yaml, chart/etcd-backup-restore/values.yaml, doc/usage/getting_started.md, pkg/snapstore/swift_snapstore.go
Signed-off-by: Rémi Collignon <remi+github@collignon-ducret.fr>
Handle regions in Swift snapstore
Fixes #295 
```improvement operator
```
=> fix(swift): region support

.ci/pipeline_definitions
prepare for switch to kaniko-builder
=> Refactor pipeline def rel v0.11.0

.ci/pipeline_definitions
Update cc/job-image-golang to 0.12.0 
Fixes #
```improvement operator
NONE
```
=> [rel-v0.12] Update cc/job-image-golang to 0.12.0

.ci/pipeline_definitions
(cherry picked from commit e2ce2525c2a2b60b09cde9b8ea735a2d506a4996)
Fixes #
Credit: @prashanth26 
```improvement operator
NONE
```
=> Update cc/job-image-golang to 0.12.0

.ci/pipeline_definitions
Cherry pick #339 on rel-v0.12
Fixes #
```improvement operator
NONE
```
=> Use testmachinery base image for integration_tests

pkg/snapstore/gcs_snapstore.go, pkg/snapstore/oss_snapstore.go, pkg/snapstore/s3_snapstore.go, pkg/snapstore/swift_snapstore.go
Cherry pick #334 334 on rel-v0.12
Fixes https://github.tools.sap/kubernetes-canary/issues-canary/issues/817
```improvement operator
Updated number of chunks while uploading to never exceed the cloud provider limits.
```
=> Updated number of chunks while uploading to never exceed the cloud provider limits.

.ci/integration_test, .ci/pipeline_definitions, .ci/tm-tests-playground, .test-defs/IntegrationTest.yaml, pkg/snapstore/snapshot.go, testmachinery/testruns/etcd/templates/testrun.yaml, testmachinery/testruns/etcd/values.yaml
This PR makes sure that the correct version of the code is pulled for TM tests on PRs. Also fixes TEST_ID generation for TM tests.
Fixes #
```improvement operator
NONE
```
=> Fix TM test location

pkg/snapshot/restorer/restorer.go
Fix bug flag --skip-hash-check not work
Fixes #
```improvement operator
```
=> Fix --skip-hash-check not work

pkg/defragmentor/defrag_test.go, pkg/snapshot/restorer/restorer_test.go, pkg/snapshot/snapshotter/snapshotter_test.go, pkg/snapstore/abs_snapstore.go, pkg/snapstore/gcs_snapstore.go, pkg/snapstore/oss_snapstore.go, pkg/snapstore/s3_snapstore.go, pkg/snapstore/swift_snapstore.go, test/e2e/integrationcluster/backup_test.go, test/e2e/integrationcluster/utils.go, test/utils/utils.go, vendor/github.com/onsi/gomega/go.mod, vendor/github.com/onsi/gomega/gstruct/elements.go, vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go, vendor/github.com/onsi/gomega/gstruct/fields.go, vendor/github.com/onsi/gomega/gstruct/ignore.go, vendor/github.com/onsi/gomega/gstruct/keys.go, vendor/github.com/onsi/gomega/gstruct/pointer.go, vendor/github.com/onsi/gomega/gstruct/types.go, vendor/modules.txt
Fixes the error in Test Machinary tests that are arising due to Backup version change for compaction support.
=> Fixed Test Machinary integration tests.

.ci/integration_test
Fixed an error in Integration Test occurred due to environment variable not found.
```
Unexpected error:
<*errors.errorString | 0xc0002c92a0>: {
s: "environment variable not found: STORAGE_CONTAINER",
}
environment variable not found: STORAGE_CONTAINER
occurred
```
Fixes #
```improvement operator
NONE
```
=> [Bug]Fixed an error occurred in Integration Test

pkg/compressor/compressor.go, pkg/snapshot/snapshotter/snapshotter.go
Some small improvements in logging of `backup-restore`.
Fixes #
```improvement operator
NONE
```
=> Some improvements in logging.

pkg/snapstore/s3_snapstore.go
Signed-off-by: Mikhail Sidorov <sidorov.ml99@gmail.com>
Fixes AWS_FORCE_PATH_STYLE env parsing
Fixes #461
=> Fix AWS_FORCE_PATH_STYLE env parsing

pkg/snapstore/s3_snapstore.go
Fixes AWS_FORCE_PATH_STYLE env parsing
Fixes #461
=> v0.15 Fix AWS_FORCE_PATH_STYLE env parsing

pkg/snapstore/swift_snapstore.go
cherry-pick of PR: https://github.com/gardener/etcd-backup-restore/pull/476
Fixes the retrieval of credentials when using the copy operation with the `Swift` snapstore.
Without this fix we get the following error when trying to copy backups:
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
A future release of golang/protobuf will delete this package,
which has long been excluded from the compatibility promise.
time="2022-05-06T10:29:51Z" level=info msg="etcd-backup-restore Version: v0.15.2"
time="2022-05-06T10:29:51Z" level=info msg="Git SHA: c9b5c3d0"
time="2022-05-06T10:29:51Z" level=info msg="Go Version: go1.17.9"
time="2022-05-06T10:29:51Z" level=info msg="Go OS/Arch: linux/amd64" …
```
=> Fixes copy operation for Swift snapstore

pkg/health/heartbeat/heartbeat.go, pkg/health/heartbeat/heartbeat_test.go, pkg/initializer/initializer.go, pkg/initializer/validator/datavalidator_test.go, pkg/leaderelection/leaderelection_test.go, pkg/member/member_control.go, pkg/member/member_control_test.go, pkg/miscellaneous/miscellaneous.go, pkg/miscellaneous/miscellaneous_test.go, pkg/miscellaneous/testdata/invalid_config.yaml, pkg/miscellaneous/testdata/valid_config.yaml, pkg/server/backrestoreserver_test.go, pkg/server/backuprestoreserver.go, pkg/snapshot/restorer/restorer.go, pkg/snapshot/restorer/restorer_test.go, pkg/snapshot/snapshotter/snapshotter_test.go, pkg/snapstore/ocs_s3_snapstore.go, test/e2e/integration/cloud_backup_test.go, test/utils/utils.go
Adds an annotation to etcd lease which indicates if the peer url is TLS enabled.
Fixes #529 
```improvement operator
Adds an annotation to etcd lease which indicates if the peer url is TLS enabled.
```
=> Enhance etcd lease to add peer url enabled status as an annotation

pkg/server/httpAPI.go
This PR handles the TLS enable case to delegate the http request from backup-restore follower to backup-restore leader to take out-of-sync full/delta snapshot.
Fixes #516
```fixbug operator
Fix a bug in handling of TLS enable case to delegate the out-of-sync snapshot request to backup-restore leader.
```
=> Handle TLS enable case to delegate the out-of-sync snapshot request to backup-restore leader.

.github/ISSUE_TEMPLATE/enhancement_request.md
If person opening the issue feel that his/her issue neither fits to new feature nor a bug, then I thought it’s better to have enhancements issue template which enhances the existing feature.
This PR adds new github issue template of enhancement.
Fixes #
```improvement operator
None
```
=> Add enhancement github issue template.

cmd/initializer.go, cmd/restore.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/initializer/initializer.go, pkg/initializer/validator/datavalidator.go, pkg/initializer/validator/validator_suite_test.go, pkg/miscellaneous/miscellaneous.go, pkg/server/backuprestoreserver.go, pkg/snapshot/restorer/restorer.go, pkg/snapshot/restorer/restorer_test.go, pkg/snapstore/abs_snapstore.go, pkg/snapstore/oss_snapstore.go, pkg/snapstore/s3_snapstore.go, pkg/snapstore/swift_snapstore.go, test/perf/regression/backup_test.go, test/perf/regression/utils.go, test/utils/utils.go
To fix checkmarxfindings: this PR handle some error unhandled error and removed some redundant code.
Fixes #
```improvement operator
None
```
=> To fix checkmarxfindings: handle some error and removed some redundant code

build/Dockerfile
/area os
Update alpine base image version to latest version `3.18.4`.
Fixes #
```improvement operator
Update alpine base image version to 3.18.4.
```
=> Update alpine base image version to 3.18.4

cmd/initializer.go, cmd/restore.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/initializer/initializer.go, pkg/initializer/validator/datavalidator.go, pkg/initializer/validator/validator_suite_test.go, pkg/miscellaneous/miscellaneous.go, pkg/server/backuprestoreserver.go, pkg/snapshot/restorer/restorer.go, pkg/snapshot/restorer/restorer_test.go, pkg/snapstore/abs_snapstore.go, pkg/snapstore/oss_snapstore.go, pkg/snapstore/s3_snapstore.go, pkg/snapstore/swift_snapstore.go, test/perf/regression/backup_test.go, test/perf/regression/utils.go, test/utils/utils.go
cherrypick of PR: https://github.com/gardener/etcd-backup-restore/pull/665
Fixes #
```improvement operator
None
```
=> [Cherrypick #665] To fix checkmarxfindings: handle some error and removed some redundant code.

pkg/initializer/initializer.go, pkg/member/member_control.go
Cherry pick: https://github.com/gardener/etcd-backup-restore/pull/661
Fixes #
```noteworthy operator
Making etcd-backup-restore restart tolerant while scaling-up an etcd cluster.
```
=> [rel-v0.24] Making etcd-backup-restore restart tolerant in between of scaling-up a cluster

pkg/server/httpAPI.go
Cherry pick of PR #675 
Fixes #
```improvement operator
The snapshots are fetched from the actual backend store when queried for latest snapshots on `/snapshot/latest` endpoint.
```
=> [rel-v0.24] Queries the actual store to fetch latest snapshot while serving the URL endpoint.

pkg/snapshot/snapshotter/garbagecollector.go, pkg/snapshot/snapshotter/snapshotter.go, pkg/snapshot/snapshotter/snapshotter_test.go, pkg/snapstore/local_snapstore.go
Cherry-pick of #685 
Fixes #
/cc @ishan16696 
```improvement operator
Add unit tests for chunk deletion
```
=> [rel-v0.24] Add unit tests for chunk deletion by garbage collector (#685)

Makefile
Cherry-pick of #700
Fixes #
@ishan16696 
```improvement operator
NONE
```
=> Fix artifact registry issue

pkg/snapshot/snapshotter/garbagecollector.go, pkg/snapshot/snapshotter/snapshotter_test.go, pkg/snapstore/snapstore_test.go, pkg/snapstore/swift_snapstore.go, pkg/snapstore/swift_snapstore_test.go
Cherry-pick of #703 
Fixes #
/invite @ishan16696 
```improvement operator
A regression in chunk deletion behavior for openstack provider has now been fixed.
```
=> [rel-v0.24] Fix regression in chunk deletion for openstack provider (#703)

build/Dockerfile
/area os
Update alpine base image version to latest version `3.18.6`.
Fixes #
```improvement operator
Update alpine base image version to 3.18.6.
```
=> Update alpine base image version to 3.18.6

README.md
Update CI Build link
Fixes #
```improvement operator
NONE
```
=> Update CI Build link

pkg/server/backuprestoreserver.go, pkg/snapshot/snapshotter/snapshotter.go, pkg/snapshot/snapshotter/snapshotter_test.go
This PR will make backup-restore to retry to take full-snapshot if previous full snapshot fails due to any reason.
Fixes #
```improvement operator
Retry to take full snapshot if the previous full snapshot operation fails.
```
=> Retry to take full snapshot if prev full snapshot fails due to some reason.

.ci/pipeline_definitions, build/Dockerfile
/area performance
/kind task
Update golang images to 1.23.4.
Fixes #
```improvement user
Update golang images to v1.23.4.
```
=> Update golang images to 1.23.4

example/01-etcd-config.yaml, pkg/health/heartbeat/heartbeat_suite_test.go, pkg/health/heartbeat/heartbeat_test.go
This PR updates the file `example/etcd-config.yaml` as etcd config parsing has changed, and also adds missing header.
Fixes #
```other operator
None
```
=> Added missing header and Updated example/etcd-config.yaml

pkg/snapshot/restorer/restorer.go
/kind cleanup
I found out that no one is using these functions, so this PR removes these functions as part of cleanup.
Fixes #
```other operator
None
```
=> Removed dead code.

.ci/pipeline_definitions, build/Dockerfile
/area security compliance quality
/kind task
Upgrade to `go1.23.6`.
Fixes #
```other developer
Upgrade to `go1.23.6`.
```
=> Upgrade to `go1.23.6`.

pkg/snapshot/restorer/restorer.go
/area disaster-recovery
/kind bug
This PR fixes a bug which causes restoration to fail when first delta snapshot completely overlaps latest full snapshot.
Fixes #844 
```bugfix user
Fixed a bug that caused restoration to fail when the first delta snapshot completely overlap with the latest full snapshot.
```
=> Fixed a bug which causes restoration to fail when first delta snapshot completely overlaps latest full snapshot.

.ci/pipeline_definitions, build/Dockerfile
/area security compliance quality
/kind task
Upgrade the concourse pipeline to `go1.24.1`.
```other developer
Upgrade the concourse pipeline to `go1.24.1`.
```
=> Upgrade the concourse pipeline to `go1.24.1`.
